<div style="text-align: center; padding: 20px; font-family: Vazir;">
<h1 align="center" style="font-size: 28px; color:rgb(64, 244, 202); width: 100%;">⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️<br>تمرین 1<br>⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️</h1>
<h2 dir='rtl' style="color:rgb(90, 255, 184); font-size: 20px;">آشنایی با توکنایزرها و N-gram</h2>
<p align="center" style="color: #666; font-size: 16px;">شهرزاد آذری آزاد - فرشاد حسامی</p>
<p align="center" style="color: #666; font-size: 16px; margin-bottom: 30px;">shahrzad.azari@ut.ac.ir - farshad.hessami@ut.ac.ir</p>

<div dir='rtl' style="border: 2px dashed rgb(90, 255, 184); border-radius: 8px; padding: 20px; margin: 20px auto; max-width: 500px; text-align: right;">
<p dir='rtl' style="color: rgb(64, 244, 202); font-size: 18px; margin-bottom: 15px;">📝 مشخصات دانشجو:</p>
<p dir='rtl' style="color: #666; margin: 5px;">نام و نام خانوادگی: امین آقاکثیری</p>
<p dir='rtl' style="color: #666; margin: 5px;">شماره دانشجویی: 810101381</p>
<p dir='rtl' style="color: #666; margin: 5px;">تاریخ ارسال: 1404/08/09</p>
</div>
</div>

<div dir="rtl" style="text-align: justify; padding: 25px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir; max-width: 100%;word-wrap: break-word;">
<div style="line-height: 2.0; font-size: 17px; color: black; font-family: Vazir;">
<div style="padding-right:40px">
در بخش‌های مختلف این تمرین با مفاهیم Tokenization, Regular Expression , N-gram Language Modeling آشنا می‌شوید و آن‌ها را پیاده‌سازی می‌کنید. 
</div>
<br>
<div style="padding-right:100px">
📋 <b>ساختار تمرین:</b>
<li><b>سوال اول - <span dir="ltr">Regular Expression & Min Distance</span> (20)</b></li>
<ul>
<li>بخش اول: تشخیص ایمیل‌های قابل قبول با Regex</li>
<li>بخش دوم: پیاده‌سازی Auto-Correction با Minimum Edit Distance</li>
</ul>
<li><b>سوال دوم - <span dir="ltr">Tokenization</span> (25)</b></li>
<ul>
<li>بخش اول: Rule-based Tokenizer</li>
<li>بخش دوم: BPE Tokenizer</li>
<li>بخش سوم: Wordpiece Tokenizer</li>
<li>بخش چهارم: Tokenization Visualization</li>
</ul>
<li><b>سوال سوم - <span dir="ltr">N-gram Language Modeling</span> (55)</b></li>
<ul>
<li>بخش اول: Data cleaning & Tokenization</li>
<li>بخش دوم: پیاده‌سازی N-gram</li>
<li>بخش سوم: معیار Perplexity</li>
<li>بخش چهارم: روش‌های هموارسازی</li>
<li>بخش پنجم: شبیه‌سازی Temperature با روش‌های هموارسازی</li>
</ul>
</div>
</div>
<div dir='rtl' style="line-height: 1.8; font-family: Vazir; font-size: 16px; margin-top: 20px; background-color: #e8eaf6; padding: 15px; border-radius: 8px; color:black">
💡 <b>نکات مهم:</b>
<br>
در متن سوالات، بخش‌هایی که در آن‌ها مجاز به استفاده از کتابخانه‌های آماده هستید ذکر شده است.
</div>
</div>

# <div style="text-align: center; direction: rtl; font-family: Vazir;"><h1 align="center" style="font-size: 24px; padding: 20px;">⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️<br>سوال اول - <span dir="ltr">Regular Expression & Min Distance</span> (20)<br>⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️</h1></div>


<p dir="rtl" style="text-align: right; padding:30px; background-color:rgb(12, 12, 12); border-radius: 12px; color: white; font-family: Vazir;">
در این سوال شما با نمونه‌هایی عملی از استفاده‌ی Regex و همینطور Minimum Distance مواجه می‌شوید. در بخش اول این سوال، شما باید ایمیل‌های قابل‌قبول را تشخیص داده و در بخش دوم سوال شما با استفاده از Minimum Distance یک سیستم Auto-Correction ساده را پیاده‌سازی خواهید کرد.


## <div style="text-align: center; direction: rtl; font-family: Vazir;">تشخیص ایمیل‌های قابل قبول با Regex</div>


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
فایل emails.txt که در اختیار شما قرار داده‌شده، شامل تعدادی اسم به‌همراه ایمیل ثبت‌شده‌‌شان در یک سامانه می‌باشد.
<br>
از شما خواسته‌شده است تا ایمیل‌هایی که معتبر هستند را با استفاده از regex مشخص کنید.
<br>
ایمیل از دو بخش تشکیل می‌شود. که با @ از هم جدا می‌شوند. بخش اول (قبل از @) local-part نام دارد و بخش دوم domain.
<br>
منظور از ایمیل معتبر این است که موارد زیر در آن‌ها رعایت شده‌باشند:
<br>
۱. دو بخش ایمیل با یک و تنها یک @ از هم جدا شده‌باشند.
<br>
۲. در local-part هم نام و هم نام خانوادگی شخص وجود داشته باشد.
<br>
۳. در local-part تنها حروف انگلیسی، اعداد و کاراکترهای -،_ و . مجاز هستند. همچنین دو نقطه نمی‌توانند پشت هم بیایند.
<br>
۴. در بخش domain یک میزبان داریم و یک پسوند. میزبان و پسوند همیشه با یک نقطه از یکدیگر جدا می‌شوند. (میزبان می‌تواند در خود نقطه داشته باشد، اما دو نقطه‌ی متوالی در domain مجاز نیست.)
<br>
۵. پسوند از حروف انگلیسی تشکیل می‌شود و حداقل دو کاراکتر دارد.
</p>


<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
- لیست ایمیل‌های قابل قبول موجود در فایل emails.txt
</p>

In [22]:
import re
def is_valid_email(email):
    email = email.strip().lower()
    if email.count('@') != 1:
        return False
    local, domain = email.split('@')

    if not local:
        return False
    if '..' in local:
        return False
    if not re.fullmatch(r'[a-z0-9._-]+', local):
        return False

    if not domain:
        return False
    if '..' in domain:
        return False
    if '.' not in domain:
        return False

    host, postfix = domain.rsplit('.', 1)
    if not host or not postfix:
        return False
    if not re.fullmatch(r'[a-z0-9.-]+', host):
        return False
    if not re.fullmatch(r'[a-z]{2,}', postfix):
        return False

    return True

def contains_name(local, full_name):
    local = local.lower()
    first_name, last_name = full_name.strip().lower().split()
    if not first_name or not last_name:
        return False
    return first_name in local and last_name in local

def get_name_and_email(line):
    m = re.match(r'name=(.+?),\s*email=(.+)\s*$', line.strip(), flags=re.IGNORECASE)
    if not m:
        return None, None
    return m.group(1).strip(), m.group(2).strip()

valid_emails = []
with open('emails.txt', 'r', encoding='utf-8') as file:
    for line in file:
        if not line.strip():
            continue
        name, email = get_name_and_email(line)
        if not name or not email:
            continue
        if not is_valid_email(email):
            continue
        local = email.split('@')[0]
        if not contains_name(local, name):
            continue
        valid_emails.append(email)

print(f"Number of valid emails: {len(valid_emails)}")
print(f"Valid emails:")
for e in valid_emails:
    print(e)

Number of valid emails: 22
Valid emails:
milad.fattahi@uni.ir
parsa.golkar@host.ir
moradi.reza@uni.ir
niloufarheidari@lab.ir
mahsa_akbari@domain.com
ali.rezaei@example.com
zarei-farhad@host.ir
hamed.jalali@net.com
ramin.shafiei@project.net
sadeghi.laleh@work.ir
nouri.pouya@mail.ir
elhamdavari@office.net
behnam.khatibi@mail.org
sara.soleimani@host.ir
shirin_hashemi@domain.com
arman.khalili@school.ir
rahaesfandiari@company.com
kiana.ghasemi@uni.edu
navid_khodadadi@research.org
mehrdad.ebrahimi@example.org
raminshafiei@project.net
hamedjalali@domain.org


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
در این بخش باید با استفاده از Regex یک تابع بنویسید که اسم یک شخص را به‌عنوان ورودی دریافت کند و درصورت وجود ایمیل معتبر برای این اسم در بین ایمیل‌های ثبت‌شده، ایمیل را برگرداند. در غیر این‌صورت، یک پیغام عدم وجود چاپ کند.
<br>
توجه: ممکن است ایمیل این اشخاص، تحت نام شخص دیگری ثبت شده باشد. کار شما این است که ایمیل معتبر این افراد را از بین تمام ایمیل‌ها پیدا کنید.
<br>
تابع را با ورودی‌های زیر اجرا کنید:
<span dir="ltr" style="text-align: left; display: block;">
name1 = Behnam Khatibi
</span>
<span dir="ltr" style="text-align: left; display: block;">
name2 = Mehrdad Ebrahimi
</span>
</p>


<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
- ایمیل‌های معتبر مربوط به افراد ذکر شده در توضیحات
</p>

In [ ]:
def find_email_by_name(name):
    is_found = False
    result = None
    for email in valid_emails:
        local = email.split('@')[0]
        if contains_name(local, name):
            result = email
            is_found = True
            break
    if is_found:
        print(f"Found email for {name}: {result}")
    else:
        print(f"No email found for {name}")

In [24]:
find_email_by_name("Behnam Khatibi")

Found email for Behnam Khatibi: behnam.khatibi@mail.org


In [25]:
find_email_by_name("Mehrdad Ebrahimi")

Found email for Mehrdad Ebrahimi: mehrdad.ebrahimi@example.org


## <div style="text-align: center; direction: rtl; font-family: Vazir;">پیاده‌سازی Auto-Correction با Minimum Edit Distance</div>


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
۱. ابتدا الگوریتم levenshtein_distance را پیاده‌سازی کنید و با استفاده از آن minimum_distance بین کلمات زیر را به‌دست آورید.
<span dir="ltr" style="text-align: left; display: block;">
pair1 = "Athletic", "Atlantic"
</span>
<span dir="ltr" style="text-align: left; display: block;">
pair2 = "London", "Boston"
</span>
<span dir="ltr" style="text-align: left; display: block;">
pair3 = "Action", "Compact"
</span>
<span dir="ltr" style="text-align: left; display: block;">
pair3 = "", "Sting"
</span>
</p>


<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
- مقدار minimum distance بین جفت کلمه‌های داده‌شده در بخش توضیحات
</p>

In [33]:
# I have considered the cost of substitution to be 2 as in the class mentioned
def calculate_min_edit_distance(source, dest, return_value=False):
    m = len(source)
    n = len(dest)
    dp = []
    for _ in range(m + 1):
        dp.append([0] * (n + 1))
    for i in range(m + 1):
        dp[i][0] = i
    for j in range(n + 1):
        dp[0][j] = j

    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if source[i - 1] == dest[j - 1]:
                dp[i][j] = dp[i - 1][j - 1]
            else:
                dp[i][j] = min(dp[i - 1][j] + 1, dp[i][j - 1] + 1, dp[i - 1][j - 1] + 2)
    if return_value:
        return dp[m][n]
    else:
        print(f"Minimum edit distance between '{source}' and '{dest}' is: {dp[m][n]}")

In [34]:
calculate_min_edit_distance("Athletic", "Atlantic")

Minimum edit distance between 'Athletic' and 'Atlantic' is: 4


In [35]:
calculate_min_edit_distance("London", "Boston")

Minimum edit distance between 'London' and 'Boston' is: 6


In [36]:
calculate_min_edit_distance("Action", "Compact")

Minimum edit distance between 'Action' and 'Compact' is: 9


In [37]:
calculate_min_edit_distance("", "Sting")

Minimum edit distance between '' and 'Sting' is: 5


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
۲. بعد از پیاده‌سازی minimum distance حال باید با استفاده از آن، جمله‌ی زیر را اصلاح املایی کنید. در این جمله تعدادی کلمه وجود دارند که املایشان نادرست است. یک لیست از املای صحیح کلمات که کلمات این جمله را نیز شامل می‌شوند در فایل vocab.txt موجود هستند.
<span dir="ltr" style="text-align: left; display: block;">
sentence_to_be_corrected = 
"helo studnts at the universty are wrting ther frst edit distnce algorthm in pythn, and they reely enjy it!"
</span>
</p>


<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
- اصلاح‌شده‌ی جمله‌ی داده‌شده در بخش توضیحات با کمک فایل vocab.txt
</p>

In [61]:
with open('vocab.txt', 'r', encoding='utf-8') as file:
    vocab_content = file.read().strip()
    vocab = []
    for word in vocab_content.split(','):
        vocab.append(word.strip())

def find_closest_word(word, vocab):
    min_distance = float('inf')
    closest_word = word
    for vocab_word in vocab:
        cure_dist = calculate_min_edit_distance(word.lower(), vocab_word.lower(), return_value=True)
        if cure_dist < min_distance:
            min_distance = cure_dist
            closest_word = vocab_word
    return closest_word

def get_correct_sentence(sentence, vocab):
    words = re.findall(r'\w+|[^\w\s]', sentence)
    correct_words = []
    for word in words:
        if word.isalpha(): 
            corrected = find_closest_word(word, vocab)
            correct_words.append(corrected)
        else:
            correct_words.append(word)
    result = ""
    i = 0
    for word in correct_words:
        if word in '.!?;:,':
            result += word
        elif i == 0:
            result += word
        else:
            result += " " + word
        i += 1
    return result

sentence = "helo studnts at the universty are wrting ther frst edit distnce algorthm in pythn, and they reely enjy it!"
print("\nBefore Correction:")
print(sentence)
corrected_sentence = get_correct_sentence(sentence, vocab)
print("\nAfter Correction:")
print(corrected_sentence)


Before Correction:
helo studnts at the universty are wrting ther frst edit distnce algorthm in pythn, and they reely enjy it!

After Correction:
hello students data they university are writing their first edit distance algorithm it Python, and they really enjoy it!


# <div style="text-align: center; direction: rtl; font-family: Vazir;"><h1 align="center" style="font-size: 24px; padding: 20px;">⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️<br>سوال دوم - <span dir="ltr">Tokenization</span> (25)<br>⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️</h1></div>


<p dir="rtl" style="text-align: right; padding:30px; background-color:rgb(12, 12, 12); border-radius: 12px; color: white; font-family: Vazir;">
در این سوال، با انواع مختلف توکنایزر و روش  پیاده‌سازی آن‌ها آشنا می‌شوید.
</p>


## <div style="text-align: center; direction: rtl; font-family: Vazir;">Rule-based Tokenizer</div>


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
با کمک دستورات regex یک توکنایزر بنویسید که متن را با استفاده از علائم نگارشی تقسیم کند.
<br>
سپس عملکرد آن را بر روی جملات داده شده زیر آزمایش کنید.
<span dir="ltr" style="text-align: left; display: block;">
"Hello, world! NLP is fun."
</span>
<span dir="ltr" style="text-align: left; display: block;">
"That U.S.A. poster-print costs $12.40..."
</span>
</p>


<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
- تعداد و لیست توکن‌های ایجادشده با توکنایزر صورت سوال برای هر جمله<br>
</p>

In [ ]:
def tokenize_with_punctuation(text):
    tokens = re.split(r'([.!?;:,-])', text)
    return tokens

sentence1 = "Hello, world! NLP is fun."
sentence2 = "That U.S.A. poster-print costs $12.40..."

tokens1 = tokenize_with_punctuation(sentence1)
print(f"Sentence 1: {sentence1}")
print(f"Number of tokens: {len(tokens1)}")
print(f"Tokens: {tokens1}\n")

tokens2 = tokenize_with_punctuation(sentence2)
print(f"Sentence 2: {sentence2}")
print(f"Number of tokens: {len(tokens2)}")
print(f"Tokens: {tokens2}")

Sentence 1: Hello, world! NLP is fun.
Number of tokens: 7
Tokens: ['Hello', ',', ' world', '!', ' NLP is fun', '.', '']

Sentence 2: That U.S.A. poster-print costs $12.40...
Number of tokens: 17
Tokens: ['That U', '.', 'S', '.', 'A', '.', ' poster', '-', 'print costs $12', '.', '40', '.', '', '.', '', '.', '']


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
ایرادات این توکنایزر چیست؟
<br>
چند راه‌حل برای بهبود عملکرد این توکنایزر ارائه دهید.
<br>
یکی از آن‌ها را پیاده‌سازی کنید.
<br>
عملکرد توکنایزر جدید را بر روی جملات داده شده آزمایش کنید.
<span dir="ltr" style="text-align: left; display: block;">
"Hello, world! NLP is fun."
</span>
<span dir="ltr" style="text-align: left; display: block;">
"That U.S.A. poster-print costs $12.40..."
</span>
</p>


<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
- تعداد و لیست توکن‌های ایجادشده با توکنایزر بهبودیافته برای هر جمله
</p>

In [ ]:
def improved_tokenizer(text):
    pattern = r'''
        \$?\d+(?:\.\d+)?  # currency and decimal numbers
        |[A-Z](?:\.[A-Z])+\.?  # abbreviations
        |\w+(?:-\w+)*  # regular words and hyphenated words
        |\.{2,}   # 3 dots
        |[^\w\s] # punctuations
    '''
    tokens = re.findall(pattern, text, re.VERBOSE)
    return tokens

sentence1 = "Hello, world! NLP is fun."
sentence2 = "That U.S.A. poster-print costs $12.40..."

tokens1_improved = improved_tokenizer(sentence1)
print(f"Sentence 1: {sentence1}")
print(f"Number of tokens (improved): {len(tokens1_improved)}")
print(f"Tokens (improved): {tokens1_improved}\n")
tokens2_improved = improved_tokenizer(sentence2)
print(f"Sentence 2: {sentence2}")
print(f"Number of tokens (improved): {len(tokens2_improved)}")
print(f"Tokens (improved): {tokens2_improved}")

Sentence 1: Hello, world! NLP is fun.
Number of tokens (improved): 8
Tokens (improved): ['Hello', ',', 'world', '!', 'NLP', 'is', 'fun', '.']

Sentence 2: That U.S.A. poster-print costs $12.40...
Number of tokens (improved): 6
Tokens (improved): ['That', 'U.S.A.', 'poster-print', 'costs', '$12.40', '...']


<div dir="rtl" style="
  background:#fffbe6;
  font-family: Vazir;
  border:1px dashed #f0ad4e;
  padding:12px;
  border-radius:8px;
  color:#111;
  line-height:1.9;
  overflow:auto;          
  max-width:100%;
  box-sizing:border-box;
">
✍️ <b>پاسخ تشریحی زیربخش اول:</b><br>

<p>
مشکل این است که صرف جدا سازی بر اساس علایم نگارشی مناسب نمی باشد زیرا بعضی علایم نگارشی خودشان جزوی از یک عبارت یا کلمه به خصوص هستند و جداسازی بر اساس آنها باعث می شود که آن عبارت یا مقدار یا کلمه، تکه تکه شده و معنی خود را از دست بدهد. همچنین جداسازی باید به صورت همزمان بر اساس اسپیس هم صورت گیرد تا کلمات به درستی از هم تفکیک شوند.
</p>

<p>
در واقع کد اولیه ای که نوشتم صرفا روی نشانه‌های [.!?;:,-] توکنایز می کند. همین انتخاب ساده باعث شد خروجی‌ها پر از اشکال باشند: فاصله‌ها به‌جای حذف، همراه توکن بعدی آمدند (" world" و " NLP is fun")، ته خروجی رشته‌های خالی تولید شد، مخفف‌ها مثل U.S.A به سه قطعهٔ بی‌معنی شکستند، عدد دارای ممیز و پیشوند ارزی ($12.40) خرد شد، واژه خط تیره‌دار (poster-print) نصف شد و سه‌نقطه پایان جمله نیز به چند نقطه متوالی تبدیل گردید. این‌ها یعنی توکنایزر نه به قواعد نوشتاری حساس است و نه حتی کمترین پاکیزگی خروجی (حذف فاصله و تهی) را رعایت می‌کند؛ صرفا هر جا punctuation دید جدا می کند.
</p>

<p>
برای درست‌کردن ماجرا باید قبل از توکنایز کردن، الگوهای معتبر را به‌صورت مثبت شناسایی کنیم و با re.findall همان‌ها را برداریم؛ یعنی به‌جای اینکه بگوییم هر جا نقطه دیدی جدا کن، بگوییم «این‌ها توکن‌اند: عددهای ارزی و اعشاری، مخفف‌های نقطه‌دار، واژه‌های معمولی و واژه‌های خط‌تیره‌دار، سه‌نقطهٔ متوالی، و در نهایت هر نشانه نگارشی منفرد». وقتی توکن‌ها را این‌گونه تعریف کنیم، هم مخفف‌ها یک‌تکه می‌مانند، هم اعداد پولی و اعشاری جدا نمی‌شوند، هم خط‌تیره بخشی از واژه محسوب می‌شود و هم سه‌نقطه به‌صورت یک توکن ثبت می‌شود؛ ضمن اینکه خبری از فاصله‌های چسبیده و رشته‌های خالی هم نخواهد بود.
</p>

<p>
پیاده‌سازی ای که انجام دادم دقیقا همین استراتژی را اعمال می‌کند: ابتدا عددهای دلاری و اعشاری را می‌گیرد، بعد مخفف‌های حروف بزرگ نقطه‌دار را یک‌جا جمع می‌کند، سپس واژه‌های معمولی و خط‌تیره‌دار را برمی‌دارد، سه‌نقطه را یک توکن می‌داند و در نهایت هر نشانه تکی را می‌گیرد.
</p>

<p>
خروجی توکن‌ها تمیز و معنادار است؛ جمله اول به ['Hello', ',', 'world', '!', 'NLP', 'is', 'fun', '.'] شکسته می‌شود و جمله دوم به ['That', 'U.S.A.', 'poster-print', 'costs', '$12.40', '...']. در این نتیجه دیگر خبری از رشته‌های تهی، فاصله‌های چسبیده، یا خردشدن توکن‌های استاندارد مثل U.S.A. و $12.40 نیست و خط‌تیره نیز درست به‌عنوان بخش واژه حفظ شده است.
</p>

<p>
اگر بخواهیم این توکنایزر را باز هم پر‌بازده‌تر کنیم، می‌توانیم چند مسیر ارتقا را در نظر بگیریم: تعمیم الگوی مخفف‌ها به حروف کوچک و الگوهایی مثل e.g. و i.e.، پشتیبانی از قالب‌های عددی با کاما (1,234.50) یا درصد و علائم واحد، شناسایی URL/ایمیل/هشتگ، و—اگر متن چندزبانه است—حرکت به‌سوی الگوهای یونیکد‌ محور (برای حروف غیرلاتین). اما برای مسئلهٔ داده‌شده، همین الگوی فعلی (که مشابه آن هم در اسلاید های درس موجود است) خطاهای بنیادی توکنایزر اولیه را حذف کرده و رفتاری معقول و پایدار روی نمونه‌جملات حاصل می‌کند.
</p>

</div>

## <div style="text-align: center; direction: rtl; font-family: Vazir;">BPE Tokenizer</div>


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
ابتدا دیتاست TinyStories-Farsi را از HuggingFace لود کنید.
<a href="https://huggingface.co/datasets/taesiri/TinyStories-Farsi" target="_blank" rel="noopener noreferrer" style="color: #9EEAD2; text-decoration: underline;">
    (لینک دیتاست)
</a>
<br>
سپس از داده آموزش (train) آن جملات فارسی را در یک لیست اضافه کنید.
<br>
اکنون با استفاده از این مجموعه داده، یک توکنایزر BPE آموزش دهید. استفاده از کتابخانه‌های آماده مانعی ندارد.
<br>
عملکرد توکنایزر را روی جمله زیر آزمایش کنید:
<br>
"روزی یک مرد ثروتمند، پسر بچه کوچکش را بـه ده برد تا بـه او نشان دهد مردمی که در آنجا زندگی می‌کنند، چقدر فقیر هستند."
</p>


<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
- مجموعه داده آموزش<br>
- تعداد و لیست توکن‌های ایجادشده برای جمله
</p>

In [1]:
from datasets import load_dataset
ds = load_dataset("taesiri/TinyStories-Farsi", split="train") 
texts = [row["Persian"] for row in ds if row.get("Persian") and row["Persian"].strip()]
print(f"Loaded {len(texts)} training samples")

/home/amin/.local/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Loaded 124411 training samples


In [2]:
import re
from tokenizers import Tokenizer
from tokenizers.models import BPE
from tokenizers.pre_tokenizers import ByteLevel
from tokenizers.decoders import ByteLevel as ByteLevelDecoder
from tokenizers.trainers import BpeTrainer
from tokenizers.normalizers import Sequence, NFC, Replace, Strip

In [3]:
bpe_tokenizer = Tokenizer(BPE(unk_token="[UNK]"))
bpe_tokenizer.normalizer = Sequence([
    NFC(),                      
    Replace("ك", "ک"),           
    Replace("ي", "ی"),         
    Replace("\u0640", ""),      # remove tatweel(_). I saw character level and unnecessary tokens when not removing it 
    Strip()])
bpe_tokenizer.pre_tokenizer = ByteLevel()
bpe_tokenizer.decoder = ByteLevelDecoder()  
trainer = BpeTrainer(
    vocab_size=32000,
    special_tokens=["[PAD]","[UNK]","[BOS]","[EOS]"]
)
bpe_tokenizer.train_from_iterator(texts, trainer=trainer)

In [25]:
sentence = "روزی یک مرد ثروتمند، پسر بچه کوچکش را بـه ده برد تا بـه او نشان دهد مردمی که در آنجا زندگی می‌کنند، چقدر فقیر هستند."
encoded = bpe_tokenizer.encode(sentence)
print("Sentence:", sentence)              
print("Ids:", encoded.ids)
print(f"Tokens (count = {len(encoded.tokens)}):", encoded.tokens)
tokens = [bpe_tokenizer.decode([i]) for i in encoded.ids]
print("Tokens (Readable):", tokens)          
rec = bpe_tokenizer.decode(encoded.ids)
print("Correctly Decoded:", rec)

Sentence: روزی یک مرد ثروتمند، پسر بچه کوچکش را بـه ده برد تا بـه او نشان دهد مردمی که در آنجا زندگی می‌کنند، چقدر فقیر هستند.
Ids: [403, 225, 485, 2150, 201, 533, 592, 2172, 204, 202, 799, 405, 308, 202, 213, 693, 744, 5608, 238, 228, 909, 444, 197, 188, 705, 201, 1370, 3479, 668, 13]
Tokens (count = 30): ['ĠØ±ÙĪØ²ÛĮ', 'ĠÛĮÚ©', 'ĠÙħØ±Ø¯', 'ĠØ«Ø±ÙĪØªÙħÙĨØ¯', 'ØĮ', 'ĠÙ¾Ø³Ø±', 'ĠØ¨ÚĨÙĩ', 'ĠÚ©ÙĪÚĨÚ©Ø´', 'ĠØ±Ø§', 'ĠØ¨Ùĩ', 'ĠØ¯Ùĩ', 'ĠØ¨Ø±Ø¯', 'ĠØªØ§', 'ĠØ¨Ùĩ', 'ĠØ§ÙĪ', 'ĠÙĨØ´Ø§ÙĨ', 'ĠØ¯ÙĩØ¯', 'ĠÙħØ±Ø¯ÙħÛĮ', 'ĠÚ©Ùĩ', 'ĠØ¯Ø±', 'ĠØ¢ÙĨØ¬Ø§', 'ĠØ²ÙĨØ¯Ú¯ÛĮ', 'ĠÙħÛĮ', 'âĢĮ', 'Ú©ÙĨÙĨØ¯', 'ØĮ', 'ĠÚĨÙĤØ¯Ø±', 'ĠÙģÙĤÛĮØ±', 'ĠÙĩØ³ØªÙĨØ¯', '.']
Tokens (Readable): [' روزی', ' یک', ' مرد', ' ثروتمند', '،', ' پسر', ' بچه', ' کوچکش', ' را', ' به', ' ده', ' برد', ' تا', ' به', ' او', ' نشان', ' دهد', ' مردمی', ' که', ' در', ' آنجا', ' زندگی', ' می', '\u200c', 'کنند', '،', ' چقدر', ' فقیر', ' هستند', '.']
Correctly Decoded:  روزی یک مرد ثروتمند، پسر بچه کوچکش را به ده برد تا به او نشان دهد مردمی که در آنجا زند

## <div style="text-align: center; direction: rtl; font-family: Vazir;">Wordpiece Tokenizer</div>


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
درباره Wordpiece Tokenizer تحقیق کنید.
<br>
نحوه آموزش این توکنایزر را به طور دقیق شرح دهید و سپس آن را با BPE مقایسه کنید.
<br>
اکنون یک توکنایزر Wordpiece بر روی مجموعه داده خود آموزش دهید. استفاده از کتابخانه‌های آماده مانعی ندارد.
<br>
عملکرد توکنایزر را روی جمله زیر آزمایش کنید:
<br>
"روزی یک مرد ثروتمند، پسر بچه کوچکش را بـه ده برد تا بـه او نشان دهد مردمی که در آنجا زندگی می‌کنند، چقدر فقیر هستند."
</p>

<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
- تعداد و لیست توکن‌های ایجادشده برای جمله
</p>

In [8]:
from tokenizers.models import WordPiece
from tokenizers.trainers import WordPieceTrainer
from tokenizers.pre_tokenizers import Whitespace
from tokenizers.decoders import WordPiece as WordPieceDecoder

In [9]:
wp_tokenizer = Tokenizer(WordPiece(unk_token="[UNK]"))
wp_tokenizer.normalizer = Sequence([
    NFC(),                      
    Replace("ك", "ک"),           
    Replace("ي", "ی"),         
    Replace("\u0640", ""),    # remove tatweel(_)   
    Strip()
])
wp_tokenizer.pre_tokenizer = Whitespace()
wp_tokenizer.decoder = WordPieceDecoder(prefix="##")

wp_trainer = WordPieceTrainer(
    vocab_size=32000,
    special_tokens=["[PAD]", "[UNK]", "[CLS]", "[SEP]", "[MASK]"],
)

wp_tokenizer.train_from_iterator(texts, trainer=wp_trainer)

In [43]:
sentence = "روزی یک مرد ثروتمند، پسر بچه کوچکش را بـه ده برد تا بـه او نشان دهد مردمی که در آنجا زندگی می‌کنند، چقدر فقیر هستند."
encoded_wp = wp_tokenizer.encode(sentence)
print("Sentence:", sentence)
print("Ids:", encoded_wp.ids)
print(f"Tokens (count = {len(encoded_wp.tokens)}):", encoded_wp.tokens)
print("Correctly Decoded:", wp_tokenizer.decode(encoded_wp.ids))

Sentence: روزی یک مرد ثروتمند، پسر بچه کوچکش را بـه ده برد تا بـه او نشان دهد مردمی که در آنجا زندگی می‌کنند، چقدر فقیر هستند.
Ids: [688, 522, 749, 2470, 157, 795, 878, 2499, 514, 512, 1824, 691, 597, 512, 517, 971, 1026, 6077, 537, 529, 1177, 729, 1021, 157, 1591, 4185, 946, 14]
Tokens (count = 28): ['روزی', 'یک', 'مرد', 'ثروتمند', '،', 'پسر', 'بچه', 'کوچکش', 'را', 'به', 'ده', 'برد', 'تا', 'به', 'او', 'نشان', 'دهد', 'مردمی', 'که', 'در', 'آنجا', 'زندگی', 'می\u200cکنند', '،', 'چقدر', 'فقیر', 'هستند', '.']
Correctly Decoded: روزی یک مرد ثروتمند ، پسر بچه کوچکش را به ده برد تا به او نشان دهد مردمی که در آنجا زندگی می‌کنند ، چقدر فقیر هستند.


In [ ]:
# this block is without removing tatweel(_) which we can see that in the final tokens, we see some unnecessary tokens like '##ـ', '##ه'
wp_tokenizer = Tokenizer(WordPiece(unk_token="[UNK]"))
wp_tokenizer.normalizer = Sequence([
    NFC(),                      
    Replace("ك", "ک"),           
    Replace("ي", "ی"),         
    Strip()
])
wp_tokenizer.pre_tokenizer = Whitespace()
wp_tokenizer.decoder = WordPieceDecoder(prefix="##")

wp_trainer = WordPieceTrainer(
    vocab_size=32000,
    special_tokens=["[PAD]", "[UNK]", "[CLS]", "[SEP]", "[MASK]"],
)
wp_tokenizer.train_from_iterator(texts, trainer=wp_trainer)
sentence = "روزی یک مرد ثروتمند، پسر بچه کوچکش را بـه ده برد تا بـه او نشان دهد مردمی که در آنجا زندگی می‌کنند، چقدر فقیر هستند."
encoded_wp = wp_tokenizer.encode(sentence)
print("Sentence:", sentence)
print("Ids:", encoded_wp.ids)
print(f"Tokens (count = {len(encoded_wp.tokens)}):", encoded_wp.tokens)
print("Correctly Decoded:", wp_tokenizer.decode(encoded_wp.ids))




Sentence: روزی یک مرد ثروتمند، پسر بچه کوچکش را بـه ده برد تا بـه او نشان دهد مردمی که در آنجا زندگی می‌کنند، چقدر فقیر هستند.
Ids: [690, 524, 751, 2472, 157, 797, 880, 2501, 516, 167, 332, 292, 1826, 693, 599, 167, 332, 292, 519, 973, 1028, 6078, 539, 531, 1179, 731, 1023, 157, 1593, 4186, 948, 14]
Tokens (count = 32): ['روزی', 'یک', 'مرد', 'ثروتمند', '،', 'پسر', 'بچه', 'کوچکش', 'را', 'ب', '##ـ', '##ه', 'ده', 'برد', 'تا', 'ب', '##ـ', '##ه', 'او', 'نشان', 'دهد', 'مردمی', 'که', 'در', 'آنجا', 'زندگی', 'می\u200cکنند', '،', 'چقدر', 'فقیر', 'هستند', '.']
Correctly Decoded: روزی یک مرد ثروتمند ، پسر بچه کوچکش را بـه ده برد تا بـه او نشان دهد مردمی که در آنجا زندگی می‌کنند ، چقدر فقیر هستند.


<div dir="rtl" style="background:#fffbe6;font-family: Vazir;border:1px dashed #f0ad4e;padding:12px;border-radius:8px;color:#111;line-height:1.9;overflow:auto;max-width:100%;box-sizing:border-box;">✍️ پاسخ تشریحی زیربخش سوم:<br>
وردپیس یک روش توکن‌سازی زیرکلمه‌ای است که اولین بار در مدل‌هایی مثل BERT مورد استفاده قرار گرفت. هدف اصلی آن این است که واژگان را از ترکیب زیرواحدهای پرتکرار بسازد تا بتواند واژه‌های جدید و شکل‌های مختلف کلمات را با واژگان نسبتا کوچک پوشش دهد. ایده‌اش تا حدی شبیه BPE است، با این تفاوت که نحوه انتخاب جفت‌هایی که باید با هم ادغام شوند متفاوت است. در هر مرحله، وردپیس سعی می‌کند با ترکیب کاراکترها و زیرکلمه‌ها، واژگان را کامل‌تر کند.<br><br>

نحوه آموزش WordPiece:<br>

1. در ابتدا فقط کاراکترها و نشانه‌های ویژه (مثل [UNK]، [CLS] و غیره) در واژگان وجود دارند.<br>
2. متن‌ها نرمال‌سازی می‌شوند تا شکل یونیکد حروف یکسان شود (مثلا با NFC)، سپس با پیش‌توکنایزر ساده‌ای مثل شکستن بر اساس فاصله به کلمات جدا می‌شوند.<br>
3. هر کلمه به دنباله‌ای از زیرقطعات موجود در واژگان فعلی شکسته می‌شود. در شروع چون فقط کاراکترها داریم، هر کلمه به صورت رشته‌ای از کاراکترها نمایش داده می‌شود.<br>
4. در هر گام، الگوریتم زوج زیرقطعه‌هایی را که افزودن آن‌ها بیشترین بهبود را در احتمال مدل زبانی ایجاد کند، انتخاب می‌کند. معیار انتخاب در وردپیس بر اساس حداکثر درست‌نمایی (Maximum Likelihood) است، نه صرفا شمارش فراوانی ادغام‌ها مثل BPE.<br>
5. زیرواحدهایی که در وسط یا انتهای کلمه قرار می‌گیرند با پیشوندی مثل «##» مشخص می‌شوند، مانند «کتاب» که به صورت «کتا» و «##ب» نمایش داده می‌شود. این کار کمک می‌کند مرزهای درون‌کلمه‌ای مشخص بمانند.<br>
6. این فرایند تا زمانی ادامه دارد که اندازه واژگان به مقدار هدف (مثلا ۴۰ هزار) برسد یا دیگر بهبودی در مدل مشاهده نشود.<br><br>

نحوه Encoding و Decoding:<br>
در مرحله Encoding، هر واژه با روش Longest-Match-First به بلندترین زیرواحدهای موجود در واژگان تقسیم می‌شود و اگر بخش ناشناخته‌ای وجود داشته باشد، از [UNK] استفاده می‌شود. در مرحله Decoding، توکن‌هایی که با «##» شروع می‌شوند، بدون این پیشوند به هم چسبانده می‌شوند تا کلمه اصلی بازسازی شود.<br><br>

تفاوت‌های اصلی WordPiece و BPE:<br>
وردپیس به جای تکیه بر شمارش فراوانی جفت‌ها، بر اساس احتمال مدل زبانی تصمیم می‌گیرد که چه ادغامی انجام شود. در نتیجه معمولا زیرواحدهایی را انتخاب می‌کند که به بهبود مدل زبانی کمک بیشتری کنند. همچنین از پیشوند «##» برای نمایش ادامه زیرواحد درون کلمه استفاده می‌کند، در حالی که BPE ممکن است از روش‌های دیگری مثل Byte-Level استفاده کند و چنین علامتی نداشته باشد. هر دو روش به کاهش مشکل واژه‌های ناشناخته (OOV) کمک می‌کنند، اما وردپیس معمولا برای زبان‌هایی مثل فارسی که ساختار صرفی پیچیده دارند، نتایج معنادارتری تولید می‌کند. البته در هر دو روش، نرمال‌سازی دقیق حروف و کنترل نیم‌فاصله اهمیت زیادی دارد، وگرنه عملکرد مدل کاهش می‌یابد. آموزش BPE ساده‌تر و سریع‌تر است، ولی وردپیس برای مدل‌هایی که مبتنی بر حداکثر درست‌نمایی هستند (مثل BERT)، سازگاری بیشتری دارد.<br>

در زبان فارسی که پر از پسوند و پیشوند و ترکیبات مختلف است، وردپیس معمولا زیرواحدهایی را یاد می‌گیرد که مرزهای صرفی را بهتر نشان می‌دهند، بنابراین با واژگان کمتر، پوشش معنایی بهتری نسبت به BPE فراهم می‌کند. با این حال اگر پیش‌پردازش مناسب روی یونیکد و نیم‌فاصله انجام نشود، هر دو روش دچار افت عملکرد می‌شوند.
در کل اگر هدف، هماهنگی با مدل‌هایی مانند BERT و بهبود درست‌نمایی توالی‌هاست، وردپیس انتخاب طبیعی‌تری است. اما اگر سرعت و سادگی مهم‌تر باشد یا از روش Byte-Level برای پوشش تمام کاراکترها استفاده می‌کنیم، BPE گزینه خوبی است. در هر دو روش، نرمال‌سازی دقیق یونیکد، یکنواخت‌سازی حروف و مدیریت نیم‌فاصله برای متن فارسی حیاتی است.<br>

در انتها هم یک بار wordpiece را بدون حذف کردن عبارت ـ train کردم که همانطور که می بینیم،توکن های اضافه تری مانند '##ـ', '##ه' تولید شده اند و در نتیجه پیش پردازش مناسب مهم است.
</div>


## <div style="text-align: center; direction: rtl; font-family: Vazir;">Tokenization Visualization</div>


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
با استفاده از ابزار 
<a href="https://tiktokenizer.vercel.app/" target="_blank" rel="noopener noreferrer" style="color: #9EEAD2; text-decoration: underline;">
    tiktokenizer
</a>
توکن‌های تولید شده برای جمله زیر را در هر یک از مدل‌های gpt2 و gpt4 و Meta-Llama-3-8B را مشاهده و تفاوت‌ها را گزارش کنید.
<br>
"روزی یک مرد ثروتمند، پسر بچه کوچکش را بـه ده برد تا بـه او نشان دهد مردمی که در آنجا زندگی می‌کنند، چقدر فقیر هستند."
<br>
سپس در مورد توکنایزر استفاده شده در هر یک تحقیق کنید. به نظر شما علت تفاوت نتیجه آن‌ها در چیست؟
</p>

<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
- توکن‌های ایجادشده با هر توکنایزر برای جمله
</p>

![gpt2](./images/gpt2_tokenizer.png)

![gpt4](./images/gpt4_tokenizer.png)

![Llama](./images/llama_tokenizer.png)

<div dir="rtl" style="background:#fffbe6;font-family: Vazir;border:1px dashed #f0ad4e;padding:12px;border-radius:8px;color:#111;line-height:1.9;overflow:auto;max-width:100%;box-sizing:border-box;">
✍️ <b>پاسخ تشریحی زیربخش چهارم:</b><br>

<p>
طبق تصاویر مشاهده‌شده، نتیجه توکن‌سازی جمله فارسی در سه مدل مختلف تفاوت محسوسی دارد. مدل GPT-2 این جمله را به ۱۳۹ توکن، مدل GPT-4 به ۱۱۲ توکن و مدل Meta-Llama-3-8B تنها به ۴۰ توکن شکسته است. این اختلاف چشمگیر نشان می‌دهد که هر مدل از ساختار و الگوریتم متفاوتی برای توکن‌سازی استفاده می‌کند.
</p>

<p>
در مدل GPT-2، از روش کلاسیک Byte-Level BPE استفاده می‌شود (همان روشی که من هم برای BPE خودم استفاده کردم زیرا هر حرف فارسی از چند بایت تشکیل شده است و بهتر است برای یادگیری بهتر حروف، آموزش در سطح بایت صورت گیرد). در این روش، داده‌ها نه بر اساس کاراکتر بلکه بر پایه بایت‌های UTF-8 پردازش می‌شوند. از آنجا که حروف فارسی در سیستم یونیکد هرکدام از چند بایت تشکیل شده‌اند، مدل GPT-2 هر حرف را به چند واحد کوچک‌تر می‌شکند و در نتیجه، حتی جمله‌ای کوتاه می‌تواند به تعداد زیادی توکن تقسیم شود. در واقع GPT-2 هیچ درک زبانی از مرز واژه‌های فارسی ندارد و تنها توالی بایت‌ها را دنبال می‌کند. به همین دلیل، توکن‌سازی آن برای زبان‌های لاتین قابل‌قبول است اما برای زبان‌های چندبایتی مانند فارسی، عربی یا چینی ناکارآمد به شمار می‌آید.
</p>

<p>
مدل GPT-4 هرچند همچنان بر پایه همان ساختار بایتی (استفاده از همان BPE) استوار است، اما از نسخه‌ای پیشرفته‌تر به نام ChatML Tokenizer استفاده می‌کند که از خانوادهٔ tiktoken مشتق شده است. در این نسخه، واژگان مدل بسیار گسترده‌تر و چندزبانه‌تر طراحی شده و داده‌های آموزشی آن شامل زبان‌های غیرفرانسه و غیربریتانیایی نیز هست. علاوه بر این، GPT-4 برای پردازش مکالمات از قالب ویژه‌ای شامل نشانه‌هایی مانند |im_start|و |im_end| استفاده می‌کند. این ساختار سبب می‌شود که مدل بتواند بخش‌های مختلف گفتگو را از هم تفکیک کند. در نتیجه، هنگام توکن‌سازی متن فارسی، چون ترکیب‌های متداول حروف فارسی در واژگان GPT-4 از قبل وجود دارند، متن با تعداد توکن کمتر و کارایی بالاتر تجزیه می‌شود (اما همچنان اغلب توکن ها بی معنی و تک حرفی هستند). با این حال، چون هنوز اساس کار مدل بر سطح بایت است، واژه‌های فارسی گاهی به چند توکن خرد می‌شوند و این توکنایزر هنوز به‌طور کامل برای فارسی بهینه نشده است.
</p>

<p>
در مقابل، مدل Meta-Llama-3-8B از روشی کاملا متفاوت بهره می‌برد. این مدل از SentencePiece BPE استفاده می‌کند که بر پایه کاراکترهای Unicode عمل می‌کند نه بایت‌ها. این روش، برخلاف GPTها، مستقیما حروف واقعی را تشخیص می‌دهد و پیش‌پردازش آن بر اساس فاصله‌ها و نرمال‌سازی یونیکد انجام می‌شود. در این شیوه، ترکیب‌های متداول عربی و فارسی از قبل در واژگان مدل وجود دارند و بنابراین مدل می‌تواند واژه‌های فارسی را همان‌طور که هستند و نه به‌صورت تکه‌تکه، پردازش کند. به همین دلیل جمله مورد نظر تنها در ۴۰ توکن بازنمایی می‌شود، زیرا هر واژه یا ترکیب طبیعی معمولا به‌صورت یک واحد مجزا شناخته می‌شود. این موضوع نشان می‌دهد که توکنایزر SentencePiece ساختار معنایی و واژگانی زبان فارسی را به‌مراتب بهتر از روش‌های مبتنی بر بایت حفظ می‌کند.
</p>

<p>
با مقایسهٔ عملکرد این سه مدل می‌توان دید که GPT-2 در فارسی ضعیف‌ترین عملکرد را دارد، چون هیچ شناختی از مرز کلمات ندارد و هر حرف را به چند بایت تبدیل می‌کند. GPT-4 با وجود آنکه همچنان از همان نوع توکنایزر استفاده می‌کند، اما به لطف واژگان گسترده‌تر و داده‌های چندزبانه، عملکرد بهتری دارد و تعداد توکن‌ها را کاهش می‌دهد. در نهایت Meta-Llama-3 به‌دلیل استفاده از SentencePiece که بر مبنای Unicode کار می‌کند، قادر است واژه‌ها را به‌صورت معنایی‌تر و طبیعی‌تر بخش‌بندی کند و تعداد توکن‌ها را به‌شدت کاهش دهد.
</p>

<p>
بنابراین، تفاوت در تعداد توکن‌های تولیدشده مستقیما از تفاوت در واحد پایه پردازش (یعنی بایت در مقابل کاراکتر) و نوع توکنایزر ناشی می‌شود. در GPT-2 و GPT-4، الگوریتم BPE روی سطح بایت کار می‌کند، در حالی که در LLaMA-3 این کار بر اساس حروف واقعی و ترکیب‌های زبانی انجام می‌شود. در نتیجه، توکنایزرهای مبتنی بر Unicode مانند SentencePiece یا Unigram BPE برای زبان‌هایی نظیر فارسی بسیار مناسب‌تر هستند، زیرا می‌توانند نیم‌فاصله‌ها، حروف و ساختار واژگانی را به‌درستی تشخیص دهند و بازنمایی دقیق‌تری از زبان ارائه دهند.
</p>


</div>


# <div style="text-align: center; direction: rtl; font-family: Vazir;"><h1 align="center" style="font-size: 24px; padding: 20px;">⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️<br>سوال سوم - <span dir="ltr">N-gram Language Modeling</span> (55)<br>⚜️━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━⚜️</h1></div>


<p dir="rtl" style="text-align: right; padding:30px; background-color:rgb(12, 12, 12); border-radius: 12px; color: white; font-family: Vazir;">
در این سوال، با N-gram Language Modeling و آن را پیاده‌سازی می‌کنید، با استفاده از آن به تولید متن می‌پردازید. سپس با معیار perplexity و نحوه کاربرد آن آشنا می‌شوید. در نهایت الگوریتم‌های smoothing و با کاربردهای آن آشنا می‌شوید. را پیاده‌سازی می‌کنید
</p>


## <div style="text-align: center; direction: rtl; font-family: Vazir;">Data cleaning & Tokenization</div>


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
مجموعه داده 
<a href="https://huggingface.co/datasets/taesiri/TinyStories-Farsi" target="_blank" rel="noopener noreferrer" style="color: #9EEAD2; text-decoration: underline;">
    TinyStories-Farsi
</a>
- که در سوال اول نیز از آن استفاده کردید - را لود کنید.
<br>
ابتدا دادگان فارسی در مجموعه آموزش (train) آن را تمیز کرده و پیش‌پردازش‌های مورد نیاز را بر روی آن انجام دهید. (با بررسی داده‌ها، مشخص‌کنید که این دادگان به چه پیش‌پردازش‌هایی نیاز دارند.)
<br>
سپس با استفاده از BPE Tokenizer که بر روی این دادگان آموزش‌داده‌اید، دادگان پردازش‌شده را توکنایز کنید.
<br>
توکن‌های یک جمله را به انتخاب خود، چاپ کنید.
</p>


<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b>
<br>
- مجموعه داده تمیزشده فارسی
<br>
- مجموعه داده توکنایز شده فارسی
<br>
- توکن‌های یک جمله‌ی دلخواه
</p>

In [54]:
def texts_with_arabic_diacritics(text_list):
    pattern = re.compile(r"[\u0610-\u061A\u064B-\u065F\u06D6-\u06ED]")
    return [(t,i) for i, t in enumerate(text_list) if pattern.search(t)]
temp = texts
result_texts = texts_with_arabic_diacritics(temp)
print(f"{len(result_texts)} texts found containing Arabic diacritics ")
print("Some examples:")
result_texts[0:5]

20892 texts found containing Arabic diacritics 
Some examples:


[(' یک روزی یک ظرف صاف وجود داشت.آن خیلی زیبا بود. این ظرف در یک خانه کوچک با دختری به نام لیلی و مادرش زندگی می\u200cکرد. \nیک روز، لیلی و مادرش برای بازی به بیرون رفتند. قبل از رفتن، مادرش گفت: "لیلی، لطفاً در را ببند." لیلی در را بست و آنها تمام روز بازی کردند.\nوقتی برگشتند، دیدند ظرف صاف روی زمین افتاده و شکسته! لیلی و مادرش خیلی ناراحت شدند. آنها نتوانستند ظرف زیبا را تعمیر کنند. پایان.',
  7),
 (' یک روز، دخترکی به نام امی به شدت مشتاق پوشیدن لباس جدیدش بود. لباسی زیبا با رنگ\u200cهای زیاد بود. او می\u200cخواست آن را به دوستش بن نشان دهد.  \nامی به خانه بن رفت و گفت "به لباس جدیدم نگاه کن بن! مگر نیست زیبا؟" بن به لباس نگاه کرد و گفت "بله، واقعاً زیباست امی. من رنگ\u200cهایش را دوست دارم."  \nآن\u200cها تمام روز را بیرون بازی کردند، دویدن و پریدن. اما بعد امی افتاد و لباسش کثیف شد. او شروع به گریه کردن کرد. بن گفت "متأسفم امی. نمی\u200cخواستم لباست کثیف شود."  \nامی پشیمان شد که آن\u200cقدر با لباس جدیدش شدید بازی کرده است. او گفت "مشکلی نیست بن. بار دیگر مراقب خواهم بود وقتی لب

In [55]:
# example of removing Arabic diacritics
print(f"before cleaning:\n{texts[42]}\n")
temp = re.sub(r"[\u0610-\u061A\u064B-\u065F\u06D6-\u06ED]", "", texts[42])
print(f"after cleaning:\n{temp}")

before cleaning:
 یک روزی، سگ بزرگی به نام چو بود. چو دوست داشت در باران بازی کند. یک روز، چو یک گربهٔ پرخاشگر دید. گربه از باران خوشش نمی‌آمد. گربه همیشه با چو بدرفتاری می‌کرد. 
چو می‌خواست با گربه دوست شود.  او راهی برای اینکه گربه باران را دوست بدارد به فکرش رسید. چو توپ بزرگ و قرمزی پیدا کرد. او فکر کرد گربه دوست دارد با این توپ در باران بازی کند.
چو توپ را برای گربه برد. گربه به توپ نگاه کرد و بعد به چو. ولی بعد اتفاق غیرمنتظره‌ای افتاد. گربه شروع به بازی با توپ در باران کرد! چو و گربه تمام روز با هم بازی کردند. آنها بهترین دوست‌ها شدند و دیگر گربه پرخاشگر نبود.

after cleaning:
 یک روزی، سگ بزرگی به نام چو بود. چو دوست داشت در باران بازی کند. یک روز، چو یک گربه پرخاشگر دید. گربه از باران خوشش نمی‌آمد. گربه همیشه با چو بدرفتاری می‌کرد. 
چو می‌خواست با گربه دوست شود.  او راهی برای اینکه گربه باران را دوست بدارد به فکرش رسید. چو توپ بزرگ و قرمزی پیدا کرد. او فکر کرد گربه دوست دارد با این توپ در باران بازی کند.
چو توپ را برای گربه برد. گربه به توپ نگاه کرد و بعد به چو. ولی بعد اتفاق 

In [ ]:
# count ZWNJ characters in the dataset
count_zwnj = sum(text.count("\u200c") for text in texts)
print("Total ZWNJ characters:", count_zwnj)

Total ZWNJ characters: 1116558


In [12]:
def texts_with_english_words(text_list):
    pattern = re.compile(r"[A-Za-z]+")
    return [(t,i) for i, t in enumerate(text_list) if pattern.search(t)]
temp = texts  
result_texts = texts_with_english_words(temp)
print(f"{len(result_texts)} texts found containing English words ")
print("Some examples:")
result_texts[0:5]

1248 texts found containing English words 
Some examples:


[(' Here is the translation in Farsi:\n\nیه روزی روزگاری، یه کشاورز بود. این کشاورز کلاه سبزی داشت. او خیلی دوست داشت لبخند بزنه. هر روز، این کشاورز به مزرعه\u200cاش می\u200cرفت تا از حیووناتش مراقبت کنه. او گاو، خوک، و مرغ داشت. کشاورز خیلی حیووناتش رو دوست داشت، و اونا هم دوستش داشتن.  \nیه روز آفتابی، کشاورز مثل همیشه رفت مزرعه. با لبخند به حیووناتش غذا داد. اما ناگهان چیز عجیبی دید. یه قورباغه بزرگ سبز توی مزرعه بود! این قورباغه کلاه سبز کوچولویی مثل کلاه کشاورز سرش بود. کشاورز تعجب کرده بود و حیوونات کنجکاو شده بودن.  \nقورباغه به کشاورز نگاه کرد و براش لبخند زد. بعد با خوشحالی توی مزرعه می\u200cپرید و می\u200cرقصید. کشاورز می\u200cخندید و دست می\u200cزد. حیوونات هم بهشون ملحق شدن. همه یه روز خوشی با قورباغه سبز گذروندن. در آخر روز، قورباغه خداحافظی کرد و با جهیدن رفت. کشاورز و حیووناتش هرگز دوست جدیدشون، قورباغه سبز با کلاه سبز کوچولو رو فراموش نکردن.',
  65),
 (' Here is the translated text in Farsi:\n\nلیلی و تام دوقلو بودند. آنها دوست داشتند همه چیز را با هم انجام دهند. آنها ب

In [58]:
# example of removing non-Persian characters
print(f"before cleaning:\n{texts[65]}\n")
temp = re.sub(r"[^آ-یء،؛؟!.0-9\s\u200c]", " ", texts[65])
print(f"after cleaning:{temp}")

before cleaning:
 Here is the translation in Farsi:

یه روزی روزگاری، یه کشاورز بود. این کشاورز کلاه سبزی داشت. او خیلی دوست داشت لبخند بزنه. هر روز، این کشاورز به مزرعه‌اش می‌رفت تا از حیووناتش مراقبت کنه. او گاو، خوک، و مرغ داشت. کشاورز خیلی حیووناتش رو دوست داشت، و اونا هم دوستش داشتن.  
یه روز آفتابی، کشاورز مثل همیشه رفت مزرعه. با لبخند به حیووناتش غذا داد. اما ناگهان چیز عجیبی دید. یه قورباغه بزرگ سبز توی مزرعه بود! این قورباغه کلاه سبز کوچولویی مثل کلاه کشاورز سرش بود. کشاورز تعجب کرده بود و حیوونات کنجکاو شده بودن.  
قورباغه به کشاورز نگاه کرد و براش لبخند زد. بعد با خوشحالی توی مزرعه می‌پرید و می‌رقصید. کشاورز می‌خندید و دست می‌زد. حیوونات هم بهشون ملحق شدن. همه یه روز خوشی با قورباغه سبز گذروندن. در آخر روز، قورباغه خداحافظی کرد و با جهیدن رفت. کشاورز و حیووناتش هرگز دوست جدیدشون، قورباغه سبز با کلاه سبز کوچولو رو فراموش نکردن.

after cleaning:                                  

یه روزی روزگاری، یه کشاورز بود. این کشاورز کلاه سبزی داشت. او خیلی دوست داشت لبخند بزنه. هر روز، ا

In [4]:
def clean_text(text):
    text = re.sub(r'\s+', ' ', text)
    text = re.sub(r"[\u0610-\u061A\u064B-\u065F\u06D6-\u06ED]", "", text)
    translation_table = str.maketrans(
        "۰۱۲۳۴۵۶۷۸۹٠١٢٣٤٥٦٧٨٩",  
        "01234567890123456789"   
    )
    text = text.translate(translation_table)
    text = re.sub(r"[^آ-یء،؛؟!.0-9\s\u200c]", " ", text)
    text = text.strip()
    return text

cleaned_texts = []
for text in texts:
    cleaned = clean_text(text)
    if cleaned:  
        cleaned_texts.append(cleaned)

In [5]:
tokenized_dataset = []
for i, text in enumerate(cleaned_texts):
    encoded = bpe_tokenizer.encode(text)
    tokenized_dataset.append(encoded.ids)
print(f"Tokenized {len(tokenized_dataset)} texts")

Tokenized 124411 texts


In [47]:
sample = tokenized_dataset[50]
readable_tokens = [bpe_tokenizer.decode([token_id]) for token_id in sample]
print(f"\nReadable tokens: {readable_tokens}")
decoded = bpe_tokenizer.decode(sample)
print(f"\nDecoded text: {decoded}")


Readable tokens: [' باری', ' روزی', '،', ' شیری', ' قدرتمند', ' به', ' نام', ' لئو', ' وجود', ' داشت', '.', ' او', ' پادشاه', ' جنگل', ' بود', '.', ' همه', ' حیوانات', ' از', ' او', ' خوششان', ' می', '\u200c', 'آمد', '،', ' چون', ' او', ' بسیار', ' مهربان', ' بود', '.', ' لئو', ' کلید', ' ویژه', '\u200c', 'ای', ' داشت', ' که', ' می', '\u200c', 'توانست', ' هر', ' چیزی', ' را', ' باز', ' کند', '.', ' او', ' آن', ' را', ' در', ' غار', ' بزرگش', ' در', ' امان', ' نگه', ' می', '\u200c', 'داشت', '.', ' یک', ' روز', '،', ' موش', ' کوچکی', ' به', ' نام', ' مکس', ' می', '\u200c', 'خواست', ' خودش', ' هم', ' قدرتمند', ' باشد', '.', ' او', ' قصد', ' داشت', ' کلید', ' لئو', ' را', ' بردارد', ' تا', ' دری', ' را', ' باز', ' کند', ' که', ' به', ' پیروزی', ' مخفی', ' منتهی', ' می', '\u200c', 'شد', '.', ' مکس', ' بسیار', ' آرام', ' و', ' مخفی', '\u200c', 'کار', ' بود', '.', ' او', ' به', ' غار', ' لئو', ' رفت', ' و', ' وقتی', ' لئو', ' نگاه', ' نمی', '\u200c', 'کرد', '،', ' کلید', ' را', ' برداشت', '.

<div dir="rtl" style="background:#fffbe6;font-family: Vazir;border:1px dashed #f0ad4e;padding:12px;border-radius:8px;color:#111;line-height:1.9;overflow:auto;max-width:100%;box-sizing:border-box;">
✍️ <b>پاسخ تشریحی زیربخش اول:</b><br>
<p>
برای پیش پردازش، بهتر است که علائم نگارشی اصلی مانند ؟!.،؛ را حذف نکنیم زیرا BPE قابلیت جداسازی و تشخیص اینها از یکدیگر را دارد و همچنین برای تولید متن در ادامه با استفاده از n-gram ها، وجود این علائم می تواند به تولید متن با معننی و مفهوم بهتر (مانند احتمال بالای قرار گیری یک نقطه یا علامت تعجب یا سوال پس از اتمام جمله و آمدن فعل) کمک کند (کما اینکه دیتاست ورودی هم داستان های کوتاه هستند که تعدادشان هم زیاد است و علائم نگارشی هم در داستان ها خوب رعایت می شوند و همین مناسب بودن داده train از لحاظ علائم نگارشی می تواند به تولید متن بهتر و غنی تر با استفاده از n-gram کمک کند). همچنین همانطور که در نمونه های چاپ شده در قسمت قبل برای توکن های BPE دیدیم، علائم نگارشی هم به صورت درست و جدا به عنوان توکن در نظر گرفته می شوند و همین باعث می شود که در زمان اختصاص احتمال برای n-gram ها بتوانیم دنباله های معنی دار تری را با کمک گرفتن از این علائم نگارشی به عنوان نشانه ای برای پایان جمله و یا تعجب،مکث و سوال بسازیم. در واقع با توجه به تسکی که می خواهیم در ادامه با استفاده از این دیتاست انجام دهیم که همان تولید متن است، علائم نگارشی می توانند در مفهوم جمله تولید شده اثر بگذارند.
</p>

<p>
همچنین چون هدف یادگیری و تولید متن به زبان فارسی است، پس بهتر است کلمات انگلیسی از متن حذف شوند زیرا اصولا در n-gram هم ما نمی خواهیم که احتمال آمدن یک کلمه انگلیسی پس از تعدادی کلمه فارسی را بررسی کنیم. همچنین تعداد این کلمات انگلیسی در دیتاست ما هم کم است و برای همین مدل نمی تواند چیزی از آن یاد بگیرد و فقط احتمالاتی را اضافه می کند که ممکن است باعث بی معنی شدن جمله شوند. چند مورد از جملاتی که کلمات انگلیسی دارند و همچنین یک مورد از حذف آنها را در ابتدای این بخش آورده ام.
</p>

<p>
مورد دیگری که می توان در پیش پردازش انجام داد، حذف space های اضافی و پشت سر هم است زیرا وجود اینها می تواند کیفیت توکنایز کردن BPE را کاهش دهد. همچنین می توان اعداد انگلیسی را هم به فارسی تبدیل کرد تا یک نوع از ارقام در دیتاست داشته باشیم. همچنین تبدیل برخی از حروف عربی هم قبلا در train کردن BPE انجام شده است و حذف برخی از حرکات عربی هم لازم است که انجام شود که نمونه هایی از آنها هم گذاشته ام. و مورد آخر هم یک دست کردن اعداد است زیرا مثلا صفر انگلیسی و فارسی نباید دو تا توکن جدا در نظر گرفته شوند و این باعث تولید توکن اضافی می شود که در اصل باید یکسان باشند (حداقل در این دیتاست که مجموعه داستان های فارسی است).همچنین به دلیل اینکه هر رقم انگلیسی در BPE یک بایت است اما در فارسی ممکن است چندین یونیکد و چنیدین بایت باشد و همچنین به دلیل اینکه چیز هایی مانند نیم فاصله که ذاتا با شکل یونیکد در متن هستند را حفظ کردم و حذف نکردم (وجود رقم انگلیسی در یونیکد)، تصمیم گرفتم که همه اعداد درون متن ر انگلیسی کنم. درباره نیم فاصله هم به این دلیل آن را حذف نکردم که در تمام متن ها به صورت درست و صحیح رعایت شده و تعداد تکرار آن را هم در ابتدای این بخش چاپ کردم و به همین دلیل، وجود آن برای تولید متن می تواند مفید باشد.
</p>

</div>


## <div style="text-align: center; direction: rtl; font-family: Vazir;">پیاده‌سازی N-gram</div>


<p dir='rtl' style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
یک کلاس برای ساخت و آموزش N-gram بنویسید.
<br>
با استفاده از این کلاس و مجموعه داده توکنایز شده که در بخش قبل آماده کردید، 
<span dir="ltr"> 2-gram, 4-gram, 8-gram</span>
بسازید و روی مجموعه داده خود آموزش دهید.
<br>
با استفاده از مدل‌های آموزش داده شده، متن‌های 100 توکنی تولید کنید و کیفیت متون تولیدشده را با هم مقایسه کنید و تفاوت عملکرد مدل‌ها از نظر پیوستگی و روانی متون را تحلیل کنید.
</p>

<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
- مدل‌های N-gram آموزش یافته
<br>
- متن‌های 100 توکنی تولیدشده با هر N-gram
</p>

In [8]:
bos_id = bpe_tokenizer.token_to_id("[BOS]")
eos_id = bpe_tokenizer.token_to_id("[EOS]")
print(bos_id, eos_id)

2 3


In [6]:
import random
from collections import defaultdict, Counter
import numpy as np

In [ ]:
class Ngram:
    def __init__(self, n):
        self.n = n
        self.vocab = set()                   
        self.ngram = defaultdict(Counter) 
        
    def train(self, tokenized_dataset):
        print(f"Training {self.n}-gram model...")
        for text_ids in tokenized_dataset:
            # padding
            tokens = (self.n - 1) * [2] + text_ids + [3]              
            self.vocab.update(tokens)
            # building ngram
            for i in range(len(tokens) - self.n + 1):
                prev_tokens = tuple(tokens[i:i + self.n - 1])
                next_token = tokens[i + self.n - 1]
                self.ngram[prev_tokens][next_token] += 1        
        print(f"Vocabulary size after training: {len(self.vocab)}")
    
    def generate(self, length):
        final_text = (self.n - 1) * [2] 
        for _ in range(length):
            prev_tokens = tuple(final_text[-(self.n - 1):])            
            if prev_tokens in self.ngram:
                next_tokens = list(self.ngram[prev_tokens].keys())
                counts = np.array([self.ngram[prev_tokens][token] for token in next_tokens])                
                prob = counts / counts.sum()                
                next_token = np.random.choice(next_tokens, p = prob)
            else:
                # choose randomly if the context is not present
                next_token = random.choice(list(self.vocab))
            final_text.append(next_token)            
        return final_text

In [13]:
bigram_model = Ngram(n=2)
bigram_model.train(tokenized_dataset)

Training 2-gram model...
Vocabulary size after training: 26265


In [55]:
print("Text generated by 2-gram model: \n")
bigram_tokens = bigram_model.generate(length=99)
bigram_text = bpe_tokenizer.decode(bigram_tokens)
print(bigram_text)
print(f"\nNumber of tokens generated: {len(bigram_tokens)}")

Text generated by 2-gram model: 

 تام خوشحال شد. پس از گارسون نزدیک آن را به درون جعبه خز و به سارا و داخل فروشگاه، آنها هم بازی کنند تا غروب آفتاب گرم رفت تا تخته را نگه می‌ها و رفت. بهترین مکانیک به پارک رفت. می‌کردن. مرد لبخند زد و صدای بلندی دارد بیشتر؟ او دوست داشت گوشی پزشکی و محکم به نام لیلی گفت   این داستان انداخت و اسباب‌زده شد. او یک روز ایده داشت. خوشحال بود! توپ بازی می‌چرخیدن نگاه کن مامان برای مادرش

Number of tokens generated: 100


In [8]:
fourgram_model = Ngram(n=4)
fourgram_model.train(tokenized_dataset)

Training 4-gram model...
Vocabulary size after training: 26265


In [ ]:
print("Text generated by 4-gram model: \n")
fourgram_tokens = fourgram_model.generate(length=97)
fourgram_text = bpe_tokenizer.decode(fourgram_tokens)
print(fourgram_text)
print(f"\nNumber of tokens generated: {len(fourgram_tokens)}")

Text generated by 4-gram model: 

 بن و لیلی وحشت زده شد. اما بعد، گربه مصنوعی اسباب‌بازی بازی کنید. برید کنار.  تام هنوز اخمو بود، اما شپش خیلی خوب پنهان می‌شد کشف کرد. یک غافلگیری برایت داریم.  اما کنجکاوی اش خیلی زیاد بود. یک روز، دختری به نام میا وجود داشت. لکه دوست داشت بازی کنه و یه پروانه ی بزرگ و کهنه‌ای پیدا می‌کنی داخل آن چیست. دوست تام، دختر بچه‌ای که در همان تالاب زندگی می‌

Number of tokens generated: 100


In [ ]:
eightgram_model = Ngram(n=8)
eightgram_model.train(tokenized_dataset)

Training 8-gram model...
Vocabulary size after training: 26265


In [ ]:
print("Text generated by 8-gram model: \n")
eightgram_tokens = eightgram_model.generate(length=93)
eightgram_text = bpe_tokenizer.decode(eightgram_tokens)
print(eightgram_text)
print(f"\nNumber of tokens generated: {len(eightgram_tokens)}")

Text generated by 8-gram model: 

 یک روز، یک گربه کوچولو در جنگل داشت قدم می‌زد. اون یه پرنده کوچولو و ناراحت رو زمین دید. پرنده غمگین و ترسیده بود. ماکس می‌خواست با گربه شوخی کند، اما گربه خوشش نیامد. گربه دست تیم را کنار زد. تیم ناراحت شد و گفت   باشه اسپات، ادامه میدیم کچ دستی بازی کنیم.  ناگهان یک پروانه از کنارشان پرواز کرد.  واو!  تیم گفت.  بیا گنجینه رو پیدا کنیم و با هم صاحبش

Number of tokens generated: 100


<div dir="rtl" style="background:#fffbe6;font-family: Vazir;border:1px dashed #f0ad4e;padding:12px;border-radius:8px;color:#111;line-height:1.9;overflow:auto;max-width:100%;box-sizing:border-box;">
✍️ <b>پاسخ تشریحی زیربخش دوم:</b><br>
متن نمونه تولید شده ۱۰۰ توکنی برای bigram به صورت زیر است:<br>
تام خوشحال شد. پس از گارسون نزدیک آن را به درون جعبه خز و به سارا و داخل فروشگاه، آنها هم بازی کنند تا غروب آفتاب گرم رفت تا تخته را نگه می‌ها و رفت. بهترین مکانیک به پارک رفت. می‌کردن. مرد لبخند زد و صدای بلندی دارد بیشتر؟ او دوست داشت گوشی پزشکی و محکم به نام لیلی گفت این داستان انداخت و اسباب‌زده شد. او یک روز ایده داشت. خوشحال بود! توپ بازی می‌چرخیدن نگاه کن مامان برای مادرش<br>

همچنین متن نمونه تولید شده ۱۰۰ توکنی برای 4-gram به صورت زیر است:<br>
بن و لیلی وحشت زده شد. اما بعد، گربه مصنوعی اسباب‌بازی بازی کنید. برید کنار. تام هنوز اخمو بود، اما شپش خیلی خوب پنهان می‌شد کشف کرد. یک غافلگیری برایت داریم. اما کنجکاوی اش خیلی زیاد بود. یک روز، دختری به نام میا وجود داشت. لکه دوست داشت بازی کنه و یه پروانه ی بزرگ و کهنه‌ای پیدا می‌کنی داخل آن چیست. دوست تام، دختر بچه‌ای که در همان تالاب زندگی می‌<br>

و در آخر متن نمونه تولید شده ۱۰۰ توکنی برای 8-gram به صورت زیر است:<br>
یک روز، یک گربه کوچولو در جنگل داشت قدم می‌زد. اون یه پرنده کوچولو و ناراحت رو زمین دید. پرنده غمگین و ترسیده بود. ماکس می‌خواست با گربه شوخی کند، اما گربه خوشش نیامد. گربه دست تیم را کنار زد. تیم ناراحت شد و گفت باشه اسپات، ادامه میدیم کچ دستی بازی کنیم. ناگهان یک پروانه از کنارشان پرواز کرد. واو! تیم گفت. بیا گنجینه رو پیدا کنیم و با هم صاحبش<br>

قبل از توضیح تفاوت ها و ویژگی های هر روش و متن این را بگویم که به دلیل اینکه در سوال گفته شده بود حتما ۱۰۰ توکن باشد، متن ها هر سه نصفه نیمه ماندند وگرنه اگر شرط رسیدن به EOS را می گذاشتیم، پایان بندی جملات بهتر می شد. <br>

در متن تولید شده توسط مدل bigram جمله‌ها و واژه‌ها به هم چسبيده‌ اند و پيوستگی بسيار ضعيف است. چون مدل فقط دنباله‌های کوتاه دو توکنی را ياد گرفته، کلمه ها را بدون رابطه معنایی درست کنار هم می‌گذارد و در واقع انگار کلمات به صورت دو تایی و کنار هم با هم مرتبط اند و معنی دارند نه در طول بلند و کل یک جمله. در واقع متن شبيه مجموعه‌ای از جمله‌های بريده و بی ربط است که یک دفعه از يک موضوع به موضوع ديگر می‌پرد. جمله‌ها اغلب از نظر معنا و ساختار با هم ارتباط ندارند و حس يک داستان منسجم را منتقل نمی‌کنند و همچنین علائم نگارشی هم به درستی رعایت نشده اند زیرا رعایت آنها نیازمند فهم درست از ساختار جمله است که با نگاه کردن به فقط یک کلمه قبلی به خوبی صورت نمی گیرد.<br>

در مدل 4-gram وضع بهتر می‌شود. چون طول توالی بيشتر است، عبارات متداول و جمله‌های کوتاه طبيعی‌تر به نظر می‌رسند. با اين حال هنوز هم پرش‌های ناگهانی در معنا ديده می‌شود و داستان به صورت ناهماهنگ پيش می‌رود. جمله‌ها در سطح محلی روان‌تر شده‌اند اما انسجام کلی هنوز ضعيف است. بعضی مواقع موضوعات و شخصيت‌ ها بدون مقدمه عوض می‌شوند و متن يکدستی خود را از دست می‌دهد.<br>

در مدل 8-gram پيوستگی و روانی به شکل محسوسی بهتر می‌ شود و همانطور که می بینیم، هر جمله به جمله قبلی خود بسیار مرتبط است و پیوستگی بیشتر شده است. مدل می‌تواند وابستگی‌های بلندمدت را تشخيص دهد، جمله‌ها به هم مربوط می‌شوند و جريان داستان نرم‌تر پيش می‌رود. در اين متن، معرفی و ادامه ماجرا منطقی‌تر است و روابط ميان شخصيت‌ها قابل دنبال کردن است. همچنین در این مدل قواعد نگارشی و علائم نگارشی هم بهتر رعایت شدند و همچنین مثلا کلمه "کنارشان" به درستی تشخیص داده شده که بیشتر از یک نفر بودند که "شان" استفاده شده است. حس داستانی و گفت‌وگو در متن ديده می‌شود و ساختار جمله‌ها طبيعی‌تر است. البته مشکلی که این مدل نسبت به دوتای قبلی دارد این است که خیلی به داده train وابسته می شود زیرا طول context window بسیار بلند است و همچنین در خیلی از مواقع هم ممکن است جمله مورد نظر اصلا در train نیامده باشد و بنابراین طبق کدی که نوشتم، کلمه بعدی به صورت رندوم (با توزیع یکنواخت) تولید می شود. در کل اگر n را خیلی زیاد کنیم، تنوع تولید متن نسبت به متن های موجود در train کمتر می شود اما پیوستگی و انسجام بالاتر می رود.
</div>


## <div style="text-align: center; direction: rtl; font-family: Vazir;">معیار Perplexity</div>


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
ابتدا از مجموعه داده 
<a href="https://huggingface.co/datasets/taesiri/TinyStories-Farsi" target="_blank" rel="noopener noreferrer" style="color: #9EEAD2; text-decoration: underline;">
    TinyStories-Farsi
</a>
دادگان validation فارسی را جدا کنید.
<br>
سپس معیار Perplexity را برای هر کدام از N-gram های خود، روی این مجموعه حساب کنید.
<br>
تحلیل خود را از این نتیجه بگویید.
</p>


<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
- مجموعه دادگان فارسی validation
<br>
- نتیجه معیار Perplexity در هر N-gram
</p>

In [6]:
from datasets import load_dataset
ds = load_dataset("taesiri/TinyStories-Farsi", split="validation") 
val_texts = [row["Persian"] for row in ds if row.get("Persian") and row["Persian"].strip()]
print(f"Loaded {len(val_texts)} validation samples")

Loaded 27630 validation samples


In [ ]:
val_texts[0:5]

[' ترجمه به فارسی:\n\nمجبور نیستی از سگ بلند صدا ترسیده باشی، من ازت محافظت میکنم. خرگوش خاکی با دخترک احساس امنیت زیادی می\u200cکرد. او خیلی مهربان بود و خرگوش خاکی به زودی به او اعتماد پیدا کرد. او به دخترک تکیه داد و دخترک از او محافظت کرد. خرگوش خاکی بهترین دوستش را پیدا کرده بود.',
 ' یک روز در یک جای گرم و آفتابی، یک چاله بزرگ وجود داشت. یک پسر کوچک به اسم تام دوست داشت نزدیک این چاله بازی کند. یک روز، تام توپ قرمزش را گم کرد. او خیلی ناراحت بود.  \nتام از دوستش، سام، خواست که به او کمک کند توپ را پیدا کند. آنها همه جا را گشتند، اما نتوانستند توپ را پیدا کنند. تام گفت: "فکر می\u200cکنم توپم توی چاله افتاده."  \nسام و تام نزدیک چاله رفتند. آنها ترسیده بودند، اما می\u200cخواستند توپ قرمز را پیدا کنند. آنها داخل چاله را نگاه کردند، اما خیلی تاریک بود و چیزی نمی\u200cدیدند. تام گفت: "باید داخل برویم و توپم را پیدا کنیم."  \nآنها داخل چاله رفتند تا جستجو کنند. تاریک و ترسناک بود. آنها نتوانستند توپ را پیدا کنند. سعی کردند بیرون بروند، اما چاله خیلی عمیق بود. تام و سام در چاله گیر افتا

In [7]:
cleaned_val_texts = []
for text in val_texts:
    cleaned = clean_text(text)
    if cleaned:  
        cleaned_val_texts.append(cleaned)

In [8]:
tokenized_val_dataset = []
for i, text in enumerate(cleaned_val_texts):
    encoded = bpe_tokenizer.encode(text)
    tokenized_val_dataset.append(encoded.ids)
print(f"\nTokenized {len(tokenized_val_dataset)} validation texts")


Tokenized 27629 validation texts


In [ ]:
def calculate_perplexity_product(model, tokenized_texts):
    product_prob = 1.0  
    total_tokens = 0
    for text_ids in tokenized_texts:
        tokens = (model.n - 1) * [2] + text_ids + [3]        
        for i in range(len(tokens) - model.n + 1):
            prev_tokens = tuple(tokens[i:i + model.n - 1])
            next_token = tokens[i + model.n - 1]            
            if prev_tokens in model.ngram and next_token in model.ngram[prev_tokens]:
                count = model.ngram[prev_tokens][next_token]
                total = model.prev_tokens_count[prev_tokens]
                prob = count / total
            else:
                prob = 1 / len(model.vocab)            
            product_prob *= prob
            total_tokens += 1
    perplexity = (1 / product_prob) ** (1 / total_tokens)
    return perplexity, total_tokens

In [20]:
print("Calculating perplexity for 2-gram model...")
bigram_perplexity = calculate_perplexity_product(bigram_model, tokenized_val_dataset)
print(f"2-gram Perplexity: {bigram_perplexity:.2f}")

Calculating perplexity for 2-gram model...


ZeroDivisionError: float division by zero

Method 1 (Product):
$$\text{Perplexity} = \left(\frac{1}{\prod P(w_i)}\right)^{1/N}$$

Method 2 (log):
$$\log_2(\text{Perplexity}) = \frac{1}{N} \log_2\left(\frac{1}{\prod P(w_i)}\right)$$

$$= \frac{1}{N} \left[\log_2(1) - \log_2\left(\prod P(w_i)\right)\right]$$

$$= \frac{1}{N} \left[0 - \sum \log_2 P(w_i)\right]$$

$$= -\frac{1}{N} \sum \log_2 P(w_i)$$

$$\text{Perplexity} = 2^{-\frac{1}{N}\sum \log_2 P(w_i)}$$

In [ ]:
def calculate_perplexity_log(model, tokenized_texts):
    total_log_prob = 0
    total_tokens = 0
    for text_ids in tokenized_texts:
        tokens = (model.n - 1) * [2] + text_ids + [3]        
        for i in range(len(tokens) - model.n + 1):
            prev_tokens = tuple(tokens[i:i + model.n - 1])
            next_token = tokens[i + model.n - 1]            
            if prev_tokens in model.ngram and next_token in model.ngram[prev_tokens]:
                count = model.ngram[prev_tokens][next_token]
                total = model.prev_tokens_count[prev_tokens]
                prob = count / total
            else:
                prob = 1 / len(model.vocab)
            total_log_prob += np.log2(prob)
            total_tokens += 1    
    perplexity = 2 ** (-1 * total_log_prob / total_tokens)
    return perplexity

In [62]:
uni = Ngram(n=1)
uni.train(tokenized_dataset)
print("Calculating perplexity for 1-gram model...")
uni_perplexity = calculate_perplexity_log(uni, tokenized_val_dataset)
print(f"1-gram Perplexity: {uni_perplexity:.2f}")

Training 1-gram model...
Vocabulary size after training: 26264
Calculating perplexity for 1-gram model...
1-gram Perplexity: 386.76


In [22]:
print("Calculating perplexity for 2-gram model...")
bigram_perplexity = calculate_perplexity_log(bigram_model, tokenized_val_dataset)
print(f"2-gram Perplexity: {bigram_perplexity:.2f}")

Calculating perplexity for 2-gram model...
2-gram Perplexity: 51.45


In [23]:
three_model = Ngram(n=3)
three_model.train(tokenized_dataset)
print("Calculating perplexity for 3-gram model...")
three_model_perplexity = calculate_perplexity_log(three_model, tokenized_val_dataset)
print(f"3-gram Perplexity: {three_model_perplexity:.2f}")

Training 3-gram model...
Vocabulary size after training: 26265
Calculating perplexity for 3-gram model...
3-gram Perplexity: 40.01


In [23]:
print("\nCalculating perplexity for 4-gram model...")
fourgram_perplexity = calculate_perplexity_log(fourgram_model, tokenized_val_dataset)
print(f"4-gram Perplexity: {fourgram_perplexity:.2f}")


Calculating perplexity for 4-gram model...
4-gram Perplexity: 86.54


In [24]:
print("\nCalculating perplexity for 8-gram model...")
eightgram_perplexity = calculate_perplexity_log(eightgram_model, tokenized_val_dataset)
print(f"8-gram Perplexity: {eightgram_perplexity:.2f}")


Calculating perplexity for 8-gram model...
8-gram Perplexity: 4777.97


<div dir="rtl" style="background:#fffbe6;font-family: Vazir;border:1px dashed #f0ad4e;padding:12px;border-radius:8px;color:#111;line-height:1.9;overflow:auto;max-width:100%;box-sizing:border-box;">
✍️ <b>پاسخ تشریحی زیربخش سوم:</b><br>
ابتدا تابع calculate_perplexity_product را برای محاسبه perplexity نوشتم که مطابق فرمولی بود که سر کلاس برای آن گفته شده بود. اما مشکلش این بود که مخرج در اثر ضرب احتمالات در هم بسیار کوچک می شد و در نهایت  underflow کرد و به صفر رسید.<br>

برای رفع این مشکل، از روش log استفاده کردم که در آن به جای ضرب احتمالات، لگاریتم آنها را جمع می کنیم و سپس در نهایت با استفاده از توان گرفتن، perplexity را محاسبه می کنیم. این روش از نظر عددی پایدارتر است و از بروز underflow جلوگیری می کند. یک توضیحی هم درباره context هایی که کلا در دیتاست ما نیامده بدهم. برای اینها، من احتمال کوچک 1/len(vocab) را در نظر گرفتم که احتمال صفر نشود. التبه این در نظر گرفتن احتمال کوچک خیلی صحیح نیست و در قسمت 3 با روش های smoothing به صورت اصولی تر این مشکل حل می شود.<br>

برای اینکه بهتر متوجه روند بهبود و ضعیف شدن مدل بشوم، برای unigram و 3-gram هم حساب کردم. در واقع عدد perplexity نشان می دهد که مدل به صورت میانگین چند کلمه با احتمال یکسان را در هر مرحله برای انتخاب به عنوان کلمه بعدی در نظر می گیرد و طبیعتا هر چقدر کمتر باشد، یعنی مدل با احتمال بالاتری کلمه بعدی را انتخاب می کند.<br>

در مدل unigram که فقط بر اساس فراوانی کلی واژه‌ها عمل می‌کند، مقدار perplexity برابر با 388 به دست آمده است. این مقدار زیاد نشان می‌دهد که مدل تقریبا به‌صورت تصادفی پیش‌بینی می‌کند و هیچ اطلاعی از وابستگی بین کلمات ندارد.<br>

در مدل bigram مقدار perplexity به حدود 51 کاهش یافته است. این به آن معناست که مدل توانسته است با درنظر گرفتن یک کلمه‌ی قبلی، احتمال واژه‌ی بعدی را با دقت بسیار بیشتری تخمین بزند.<br>

در مدل  3-gram مقدار perplexity به حدود 40 رسیده است که کمترین مقدار بین همه‌ی مدل‌هاست. در این حالت مدل دو کلمه‌ی قبلی را در نظر می‌گیرد و همین باعث می‌شود که روابط نحوی و معنایی کوتاه‌مدت را بهتر درک کند. این مدل بهترین تعادل را بین داشتن زمینه‌ کافی و داشتن داده‌ کافی برای آموزش حفظ کرده است.<br>

در مدل 4-gram مقدار perplexity دوباره افزایش یافته و به حدود 86 رسیده است. دلیل این افزایش آن است که بسیاری از چهار‌تایی‌های متوالی در داده‌ی آموزش وجود نداشته‌اند و مدل هنگام پیش‌بینی روی داده‌ی جدید با ترکیب‌هایی روبه‌رو می‌شود که آن‌ها را ندیده است. این پدیده همان مشکل کمبود داده یا sparsity است.<br>

در مدل 8-gram این مشکل بسیار شدیدتر می‌شود و perplexity به حدود 4777 می‌رسد. در این حالت تقریبا هیچ‌ یک از دنباله‌های هفت‌ کلمه‌ ای پیش از هر کلمه در داده‌ی آموزش وجود نداشته و بنابراین مدل در مواجهه با متن جدید تقریبا هیچ اطمینانی در پیش‌بینی ندارد و در واقع هر کلمه به شرط ۷ کلمه قبلی خود احتمال بسیار کوچک و یا صفر دارد که در آن صورت هم با توزیع یکنواخت از بین کلمات انتخاب می شود و این احتمال های کوچک باعث افزایش perplexity می شوند.<br>

در نتیجه می‌توان گفت که با افزایش طول n، مدل در ابتدا بهتر عمل می‌کند زیرا اطلاعات بیشتری از جمله‌ی قبلی دارد، اما وقتی n بیش از حد بزرگ شود، مدل بیش از اندازه محدود به داده‌های آموزش می‌شود و توانایی تعمیم خود را از دست می‌ دهد. در این مجموعه داده‌ی خاص، مدل 3-gram بهترین عملکرد را از نظر معیار perplexity داشته است و تعادلی میان دقت و پوشش داده برقرار کرده است.

</div>


<p dir='rtl' style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
در این قسمت چهار جمله در اختیار شما قرار گرفته است. استدلال کنید کدام جمله‌ها محتمل‌ترند که توسط یک <span dir="ltr">4-gram</span> که روی داده‌های مشابه آموزش دیده‌است، تولید شده باشند.
<br>
جمله‌ی اول = آنها دوست داشتند در ماسه بازی کنند و جزر و مد آب را تماشا کنند
<br>
جمله‌ی دوم = جیل و تام به همراه مامان و بابا به ساحل رفتند
<br>
جمله‌ی سوم = تام بطری‌ نوشابه‌ را تا حد ممکن بالا انداخت و به سمت او فریاد زد
<br>
جمله‌ی چهارم = باری خیلی دوست داشت بیرون از منزل نقاشی کند و با پدربزرگ منظره تماشا کند
</p>

In [15]:
test_sentences = [
    "آنها دوست داشتند در ماسه بازی کنند و جزر و مد آب را تماشا کنند",
    "جیل و تام به همراه مامان و بابا به ساحل رفتند",
    "تام بطری نوشابه را تا حد ممکن بالا انداخت و به سمت او فریاد زد",
    "باری خیلی دوست داشت بیرون از منزل نقاشی کند و با پدربزرگ منظره تماشا کند"
]
cleaned_sentences = [clean_text(sent) for sent in test_sentences]
tokenized_sentences = [bpe_tokenizer.encode(sent).ids for sent in cleaned_sentences]


for i, tokens in enumerate(tokenized_sentences, 1):
    perp = calculate_perplexity_log(fourgram_model, [tokens])
    print(f"\nPerplexity for sentence number {i}: {perp:.2f}")


Perplexity for sentence number 1: 744.39

Perplexity for sentence number 2: 18.40

Perplexity for sentence number 3: 1975.05

Perplexity for sentence number 4: 4760.14


<div dir="rtl" style="background:#fffbe6;font-family: Vazir;border:1px dashed #f0ad4e;padding:12px;border-radius:8px;color:#111;line-height:1.9;overflow:auto;max-width:100%;box-sizing:border-box;">
✍️ <b>پاسخ تشریحی زیربخش چهارم:</b><br>

ابتدا با توجه به اعداد محاسبه شده که perplexity هر جمله را برای 4-gram نشان می دهد، متوجه می شویم که جمله دوم بیشترین احتمال را دارد که توسط 4-gram تولید شده باشد زیرا کمترین perplexity را دارد. حال می توان با تحلیل ساختار جملات به دلیل این موضوع پرداخت.<br>

جمله 2 «جیل و تام به همراه مامان و بابا به ساحل رفتند» کمترین perplexity را دارد، چون زنجیره‌های چهار کلمه ای متداول و کودکانه زیادی در آن هست: «جیل و تام»، «به همراه مامان و بابا»، «به ساحل رفتند». چنین عباراتی در داستان‌های کودکان (رفتن به ساحل با خانواده) که دیتاست train ما روی آن است، زیاد تکرار می‌شود و یک 4-gram بافت‌های پشت‌سرهم را دقیقا از روی فراوانی همان قطعه‌ها یاد می‌گیرد. برای همین تعداد زیادی از 4 توکن هایش در آموزش دیده شده‌اند و احتمال‌های شرطی‌اش بالا می‌ماند.<br>

جمله 1 «آنها دوست داشتند در ماسه بازی کنند و جزر و مد آب را تماشا کنند» موضوعش با دامنه داده سازگار است (بازی در ماسه، ساحل)، اما چند دنباله نسبتا کم‌تکرار دارد: «جزر و مد آب را»، «مد آب را تماشا». در داستان‌های کودکانه فارسی معمولا ترکیب‌های ساده‌تری مثل «امواج دریا» یا «بالا و پایین رفتن آب» می‌آید. همین باعث می‌شود چند 4-gram دیده‌نشده یا فراوانی کم در جمله ظاهر شود و perplexity نسبت به جمله 2 بالاتر برود، هرچند هنوز از 3 و 4 بهتر است چون بقیهٔ قطعه‌ها مثل «در ماسه بازی کنند» برای مدل آشنا هستند.<br>

جمله 3 «تام بطری نوشابه را تا حد ممکن بالا انداخت و به سمت او فریاد زد» هم از نظر موضوعی و هم از نظر عبارات برای داده کودکانه نامعمول‌ تر است. دنباله‌هایی مثل «بطری نوشابه را تا»، «تا حد ممکن بالا»، «به سمت او فریاد» در داستان‌های ساده کمتر تکرار می‌شوند و حتی از نظر هم‌نشینی واژه ها هم خیلی محتمل نیستند. یک 4-gram وقتی با چنین بافت‌هایی روبه‌رو می‌شود به‌خاطر کمبود شمارش‌ها احتمال‌های خیلی کوچکی می‌دهد و perplexity بالا می‌رود.<br>

جمله 4 «باری خیلی دوست داشت بیرون از منزل نقاشی کند و با پدربزرگ منظره تماشا کند» بالاترین perplexity را دارد. احتمال دارد که اسم «باری» در داده ما کم‌تر از مثلا تام تکرار شده باشد، همچنین ترکیب‌هایی مثل «بیرون از منزل نقاشی»، «با پدربزرگ منظره تماشا» کمتر دیده شده‌اند. 4-gram به‌شدت به تطابق دقیق توالی‌های پشت‌ سر هم وابسته است. کافی است تعدادی از 4 توکن ها را ندیده باشیم تا احتمال جمله به‌شدت افت کند و perplexity افزایش یابد.
</div>


In [145]:
bari = "باری"
tom = "تام"
count_bari = sum(sentence.count(bari) for sentence in cleaned_texts)
count_tom = sum(sentence.count(tom) for sentence in cleaned_texts)
print(f"{bari} appeared {count_bari} times")
print(f"{tom} appeared {count_tom} times")

باری appeared 15264 times
تام appeared 104671 times


## <div style="text-align: center; direction: rtl; font-family: Vazir;">روش‌های هموارسازی</div>


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
هر کدام از الگوریتم‌های هموارسازی (Smoothing) که در درس خوانده‌اید (Laplace, Interpolation, Backoff) را پیاده‌سازی کنید.
<br>
یک مدل
<span dir="ltr">4-gram</span>
بسازید و با مجموعه داده توکنایزشده فارسی که در بخش اول این سوال آماده کردید، آموزش دهید.
(می‌توانید از مدل 
<span dir="ltr">4-gram</span>
آموزش‌یافته قبلی خود استفاده کنید.)
<br>
در الگوریتم Interpolation مقادیر λ را 0.4, 0.3, 0.2, 0.1 در نظر بگیرید. به این صورت:
P​(w∣h3​,h2​,h1​)=0.4P​(w∣h3​,h2​,h1​)+0.3P​(w∣h2​,h1​)+0.2P​(w∣h1​)+0.1P​(w)
<br>
در الگوریتم Backoff مقدار λ را 0.4 در نظر بگیرید.
<br>
سپس با استفاده از هر یک از این روش‌ها، متن‌هایی به طول 100 توکن تولید کنید.
<br>
متن‌های تولیدشده را با یکدیگر مقایسه کنید و تفاوت آن‌ها را از نظر روانی و تنوع کلمات بررسی کنید.
<br>
در نهایت، با استفاده از احتمالات محاسبه‌شده در هر یک از این روش‌ها، معیار Perplexity را روی مجموعه دادگان فارسی validation - که در بخش سوم این سوال آماده کردید - حساب کنید.
<br>
مقادیر Perplexity برای هر کدام از روش‌های هموارسازی و مدل غیرهموار (Unsmoothed) را با یکدیگر مقایسه کنید و تحلیل خود را از این نتایج بگویید.
</p>


<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
- متن‌های تولیدشده با هر یک از روش‌های هموارسازی ذکر شده
<br>
- معیار Perplexity برای هر یک از روش‌های هموارسازی ذکر شده
</p>

In [11]:
from collections import Counter, defaultdict
import numpy as np
import random

In [ ]:
class NgramSmoothed:
    def __init__(self, n):
        self.n = n
        self.prev_tokens_count = Counter()     
        self.vocab = set()                   
        self.ngram = defaultdict(Counter)
        self.lower_order_models = {}
        
    def train(self, tokenized_dataset):
        print(f"Training {self.n}-gram model...")
        for text_ids in tokenized_dataset:
            tokens = (self.n - 1) * [2] + text_ids + [3]              
            self.vocab.update(tokens)
            for i in range(len(tokens) - self.n + 1):
                prev_tokens = tuple(tokens[i:i + self.n - 1])
                next_token = tokens[i + self.n - 1]
                self.prev_tokens_count[prev_tokens] += 1
                self.ngram[prev_tokens][next_token] += 1        
        self.train_lower_order_models(tokenized_dataset)
        print(f"Vocabulary size after training: {len(self.vocab)}")
    
    # for backoff and interpolation
    def train_lower_order_models(self, tokenized_dataset):
        for order in range(1, self.n):
            lower_ngram = defaultdict(Counter)
            lower_context_count = Counter()
            for text_ids in tokenized_dataset:
                tokens = (order - 1) * [2] + text_ids + [3]
                for i in range(len(tokens) - order + 1):
                    if order == 1:
                        prev = ()  
                    else:
                        prev = tuple(tokens[i:i + order - 1])
                    next_token = tokens[i + order - 1]
                    lower_context_count[prev] += 1
                    lower_ngram[prev][next_token] += 1
            
            self.lower_order_models[order] = {'ngram': lower_ngram, 'count': lower_context_count}
    
    def generate(self, length, smoothing=None, lambdas=None, lambda_backoff=0.4, temperature=1.0):
        final_text = (self.n - 1) * [2]
        for _ in range(length):
            prev_tokens = tuple(final_text[-(self.n - 1):])
            if smoothing is None:
                next_token = self.generate_no_smoothing(prev_tokens, temperature)
            elif smoothing == 'laplace':
                next_token = self.generate_laplace(prev_tokens, temperature)
            elif smoothing == 'backoff':
                next_token = self.generate_backoff(prev_tokens, lambda_backoff, temperature)
            elif smoothing == 'interpolation':
                next_token = self.generate_interpolation(prev_tokens, lambdas, temperature)
            final_text.append(next_token)
        
        return final_text

    def generate_no_smoothing(self, prev_tokens, temperature=1.0):
        if prev_tokens in self.ngram:
            next_tokens = list(self.ngram[prev_tokens].keys())
            counts = np.array([self.ngram[prev_tokens][token] for token in next_tokens])
            prob = counts / counts.sum()
            prob = self.apply_temperature(prob, temperature)
            return np.random.choice(next_tokens, p=prob)
        else:
            return random.choice(list(self.vocab))

    def generate_laplace(self, prev_tokens, temperature=1.0):
        vocab_list = list(self.vocab)        
        if prev_tokens in self.prev_tokens_count:
            total_count = self.prev_tokens_count[prev_tokens]
            probs = []
            for token in vocab_list:
                count = self.ngram[prev_tokens].get(token, 0)
                prob = (count + 1) / (total_count + len(vocab_list))
                probs.append(prob)
            
            probs = np.array(probs)
            probs = probs / probs.sum() 
            probs = self.apply_temperature(probs, temperature)
            return np.random.choice(vocab_list, p=probs)
        else:
            return random.choice(vocab_list)
    
    def generate_backoff(self, prev_tokens, lambda_backoff=0.4, temperature=1.0):
        # all tokens that follow prev_tokens (context)
        candidate_tokens = set()
        if prev_tokens in self.ngram:
            candidate_tokens.update(self.ngram[prev_tokens].keys())
            
        for order in range(self.n - 1, 0, -1):
            if order == 1:
                context = ()
            else:
                context = prev_tokens[-(order - 1):]
            
            if order in self.lower_order_models:
                model = self.lower_order_models[order]
                if context in model['ngram']:
                    candidate_tokens.update(model['ngram'][context].keys())
        
        if not candidate_tokens:
            candidate_tokens = self.vocab
        
        candidated_vocab_list = list(candidate_tokens)
        scores = np.zeros(len(candidated_vocab_list))
        
        for index, token in enumerate(candidated_vocab_list):
            scores[index] = self.get_stupid_backoff_score(prev_tokens, token, lambda_backoff)

        # normalize scores
        probs = scores / scores.sum()
        probs = self.apply_temperature(probs, temperature)
        return np.random.choice(candidated_vocab_list, p=probs)
    
    def get_stupid_backoff_score(self, context, token, lambda_backoff):
        # if the probability is present
        if context in self.prev_tokens_count:
            count_context_token = self.ngram[context].get(token, 0)
            if count_context_token > 0:
                return count_context_token / self.prev_tokens_count[context]
            
        # backoff to unigram
        if len(context) == 0:
            if 1 in self.lower_order_models:
                unigram_model = self.lower_order_models[1]
                total_count = unigram_model['count'].get((), 0)
                if total_count > 0:
                    unigram_count = unigram_model['ngram'][()].get(token, 0)
                    return lambda_backoff * (unigram_count / total_count)
            return lambda_backoff / len(self.vocab)

        
        backed_context = context[1:]
        return lambda_backoff * self.get_stupid_backoff_score(backed_context, token, lambda_backoff)

    def generate_interpolation(self, prev_tokens, lambdas=None, temperature=1.0):
        vocab_list = list(self.vocab)
        vocab_index = {token: i for i, token in enumerate(vocab_list)}               
        probs = np.zeros(len(vocab_list))
        if prev_tokens in self.ngram:
            total = self.prev_tokens_count[prev_tokens]
            for token, count in self.ngram[prev_tokens].items():
                if token in vocab_index:
                    probs[vocab_index[token]] += lambdas[0] * (count / total)

        # calculate lambda * prob till unigram
        for order in range(self.n - 1, 0, -1):
            index = self.n - order
            if order == 1:
                context = ()
            else:
                context = prev_tokens[-(order - 1):]
            if order in self.lower_order_models:
                model = self.lower_order_models[order]
                if context in model['ngram']:
                    total = model['count'][context]
                    for token, count in model['ngram'][context].items():
                        if token in vocab_index:
                            probs[vocab_index[token]] += lambdas[index] * (count / total)        
        if probs.sum() > 0:
            probs = probs / probs.sum()
            probs = self.apply_temperature(probs, temperature)
            return np.random.choice(vocab_list, p=probs)
        else:
            return random.choice(vocab_list)
    
    def get_prob_laplace(self, context, token):        
        count = self.ngram[context].get(token, 0)
        total_context_count = self.prev_tokens_count.get(context, 0)
        return (count + 1) / (total_context_count + len(self.vocab))

    def get_prob_backoff(self, context, token, lambda_backoff):
        return self.get_stupid_backoff_score(context, token, lambda_backoff)

    def get_prob_interpolation(self, context, token, lambdas):
        prob = 0
        if context in self.prev_tokens_count:
            total = self.prev_tokens_count[context]
            count = self.ngram[context].get(token, 0)
            if total > 0:
                prob += lambdas[0] * (count / total)

        for order in range(self.n - 1, 0, -1):
            index = self.n - order
            if order == 1:
                lower_context = ()
            else:
                lower_context = context[-(order - 1):] 
            if order in self.lower_order_models:
                model = self.lower_order_models[order]
                if lower_context in model['count']:
                    total = model['count'][lower_context]
                    count = model['ngram'][lower_context].get(token, 0)
                    if total > 0:
                        prob += lambdas[index] * (count / total)
        return prob
        
    def calculate_perplexity(self, tokenized_texts, smoothing=None, lambdas=None, lambda_backoff=0.4):
        total_log_prob = 0
        total_tokens = 0
        vocab_size = len(self.vocab)
        
        for text_ids in tokenized_texts:
            tokens = (self.n - 1) * [2] + text_ids + [3]  
            
            for i in range(len(tokens) - self.n + 1):
                prev_tokens = tuple(tokens[i:i + self.n - 1])
                next_token = tokens[i + self.n - 1]
                prob = 0
                
                if smoothing == 'laplace':
                    prob = self.get_prob_laplace(prev_tokens, next_token)
                elif smoothing == 'backoff':
                    prob = self.get_prob_backoff(prev_tokens, next_token, lambda_backoff)
                elif smoothing == 'interpolation':
                    prob = self.get_prob_interpolation(prev_tokens, next_token, lambdas)
                elif smoothing is None:
                    if prev_tokens in self.prev_tokens_count and next_token in self.ngram[prev_tokens]:
                        count = self.ngram[prev_tokens][next_token]
                        total = self.prev_tokens_count[prev_tokens]
                        prob = count / total
                    else:
                        prob = 1 / vocab_size

                # same as I explained before (in part 2 report) for unseen context probability
                if prob == 0:
                    prob = 1 / vocab_size
                
                total_log_prob += np.log2(prob)
                total_tokens += 1
        
        avg_log_prob = total_log_prob / total_tokens
        perplexity = 2 ** (-avg_log_prob)
        
        return perplexity
    
    def apply_temperature(self, probs, temperature):
        if temperature == 1:
            return probs        
        log_probs = np.log(probs + 1e-10)
        scaled_probs = log_probs / temperature
        scaled_probs = scaled_probs - np.max(scaled_probs)
        exp_probs = np.exp(scaled_probs)
        return exp_probs / exp_probs.sum()

In [13]:
model = NgramSmoothed(n=4)
model.train(tokenized_dataset)

Training 4-gram model...
Vocabulary size after training: 26265


In [ ]:
print("Text generated by 4-gram model with no smoothing: \n")
no_smoothing_tokens = model.generate(length=100, smoothing=None)
no_smoothing_text = bpe_tokenizer.decode(no_smoothing_tokens)
print(no_smoothing_text)

Text generated by 4-gram model with no smoothing: 

 یک بار در روزگاران پیش، یک سگ به اسم اسپات بود. اسپات و پرنده به مسافرت رفتند. جان خیلی خوشحال بود. می‌توانیم با هم برقصیم؟  بن پرسید   این چه صدایی بود؟  پرسید پرنده  تخم مرغم از لانه ام دورم و خسته ام.  لیلی کمی ناراحت شد، اما می‌توانند با هم مرغ‌ها عکس گرفت. او آن را در تمام اتاق پرتاب کند. او نزد دوستان زنبورش رفت و گفت   متأسفم، اسباب‌بازی رنگارنگ ساختند


In [ ]:
print("Text generated by 4-gram model with laplace smoothing: \n")
laplace = model.generate(length=100, smoothing="laplace")
lp = bpe_tokenizer.decode(laplace)
print(lp)

Text generated by 4-gram model with laplace smoothing: 

 متن نازکه بپیوند شکره کمکی میپرسد دروغی محیط قصدت وه سبوی قطارشان غشغش بخوانید رشدش احمقم بطوری شمعد آفتابگردان ویولنی خبریخواین نمیکنند وسای پادشاهم آرزوهایشانپرکید امى امیدشختند شیطنت غذاش گذراند دربیاورید فارتوک شکارچیان محافظتیگانی چسبی خوشگلشانلنش سریع فرمانبرداری بیداری منزل بمونیم خاصیتی واکایاک بدکاره ژینا غذاىچقدرایمنی رویاهایشان سیج خاصه دیگچهزیگزاگ نامند پیوندی راهمان پزندسکا کلفتی ببیندش شیونازن استاری انداختند بذاریم چیزهای دادشان لرزید اح اهمی حا پرستارشوعده موش کراکرهاگیس آبیم اشتباهاتت خاراندند کلینیک خوشگلیه پارکر کمه هیس تنا مادران دفاع پابرجا اشپز تبربازی معلممان هدایت هشداری گردنبندهای


In [132]:
print("Text generated by 4-gram model with backoff smoothing: \n")
backoff = model.generate(length=100, smoothing="backoff")
bp = bpe_tokenizer.decode(backoff)
print(bp)

Text generated by 4-gram model with backoff smoothing: 

 یکی بود یکی نبود، یک دختر کوچک به نام آنا وجود داشت. فرد در یک چاله آب عمیق بازی کردند. آنها خیلی خوش گذراندند. بقیه حیوانات جنگل را می‌پوشید. یک روز، یک پسر به نام تیم یک درخت بزرگ و زیبا بود. لوسی دوست داشت تا شنیدند کردن داد می بازی گفت یک می پنهان می،. و یک چیز سفید روی گردنش داشت. سالی یک صابون صورتی رنگ را دیده‌ای. چرا از مطالعه مدتی استراحت نمی کنی و به زودی با هم در پارک بازی


In [140]:
lambdas = [0.4, 0.3, 0.2, 0.1] 
print("Text generated by 4-gram model with interpolation smoothing: \n")
interpolation = model.generate(length=100, smoothing="interpolation", lambdas=lambdas)
ip = bpe_tokenizer.decode(interpolation)
print(ip)

Text generated by 4-gram model with interpolation smoothing: 

 یک روز، مارک سس قرمز بود. لیلی دوست داشت که با هم بازی کردن است. اما فرد نمی‌گویند   باشه لیلی، ولی اونو برای چی هستند؟  مادرش به او را دوست داشتند. بعدا پرنده ترسناکی رفت خونه و تاجش زد و دیگر دیر شده بود. پیتزا رفته.  قهرمان آنها شده بود. لیلی دوست داشتند.. به صدای‌ یک‌پسربچه‌ای به نام جری. جری شیر را در بشقاب امروز را دوست دارم. این باغ رو ول کرد که به باغ


In [142]:
unsmoothed_perplexity = model.calculate_perplexity(tokenized_val_dataset, smoothing=None)
print(f"Unsmoothed Perplexity: {unsmoothed_perplexity:.2f}")

Unsmoothed Perplexity: 86.54


In [114]:
laplace_ppl = model.calculate_perplexity(tokenized_val_dataset, smoothing='laplace')
print(f"Laplace Perplexity: {laplace_ppl:.2f}")

Laplace Perplexity: 1783.17


In [115]:
backoff_ppl = model.calculate_perplexity(tokenized_val_dataset, smoothing='backoff', lambda_backoff=0.4)
print(f"Backoff Perplexity: {backoff_ppl:.2f}")

Backoff Perplexity: 100.54


In [116]:
interpolation_ppl = model.calculate_perplexity(tokenized_val_dataset, smoothing='interpolation', lambdas=lambdas)
print(f"Interpolation Perplexity: {interpolation_ppl:.2f}")

Interpolation Perplexity: 30.51


<div dir="rtl" style="background:#fffbe6;font-family: Vazir;border:1px dashed #f0ad4e;padding:12px;border-radius:8px;color:#111;line-height:1.9;overflow:auto;max-width:100%;box-sizing:border-box;">
✍️ <b>پاسخ تشریحی زیربخش پنجم:</b><br>

متن تولید شده بدون smoothing:<br>
 یک بار در روزگاران پیش، یک سگ به اسم اسپات بود. اسپات و پرنده به مسافرت رفتند. جان خیلی خوشحال بود. می‌توانیم با هم برقصیم؟  بن پرسید   این چه صدایی بود؟  پرسید پرنده  تخم مرغم از لانه ام دورم و خسته ام.  لیلی کمی ناراحت شد، اما می‌توانند با هم مرغ‌ها عکس گرفت. او آن را در تمام اتاق پرتاب کند. او نزد دوستان زنبورش رفت و گفت   متأسفم، اسباب‌بازی رنگارنگ ساختند
<br>
متن تولید شده با laplace:<br>
 متن نازکه بپیوند شکره کمکی میپرسد دروغی محیط قصدت وه سبوی قطارشان غشغش بخوانید رشدش احمقم بطوری شمعد آفتابگردان ویولنی خبریخواین نمیکنند وسای پادشاهم آرزوهایشانپرکید امى امیدشختند شیطنت غذاش گذراند دربیاورید فارتوک شکارچیان محافظتیگانی چسبی خوشگلشانلنش سریع فرمانبرداری بیداری منزل بمونیم خاصیتی واکایاک بدکاره ژینا غذاىچقدرایمنی رویاهایشان سیج خاصه دیگچهزیگزاگ نامند پیوندی راهمان پزندسکا کلفتی ببیندش شیونازن استاری انداختند بذاریم چیزهای دادشان لرزید اح اهمی حا پرستارشوعده موش کراکرهاگیس آبیم اشتباهاتت خاراندند کلینیک خوشگلیه پارکر کمه هیس تنا مادران دفاع پابرجا اشپز تبربازی معلممان هدایت هشداری گردنبندهای
<br>
متن تولید شده با backoff:<br>
 یکی بود یکی نبود، یک دختر کوچک به نام آنا وجود داشت. فرد در یک چاله آب عمیق بازی کردند. آنها خیلی خوش گذراندند. بقیه حیوانات جنگل را می‌پوشید. یک روز، یک پسر به نام تیم یک درخت بزرگ و زیبا بود. لوسی دوست داشت تا شنیدند کردن داد می بازی گفت یک می پنهان می،. و یک چیز سفید روی گردنش داشت. سالی یک صابون صورتی رنگ را دیده‌ای. چرا از مطالعه مدتی استراحت نمی کنی و به زودی با هم در پارک بازی
<br>

متن تولید شده با interpolation:<br>
 یک روز، مارک سس قرمز بود. لیلی دوست داشت که با هم بازی کردن است. اما فرد نمی‌گویند   باشه لیلی، ولی اونو برای چی هستند؟  مادرش به او را دوست داشتند. بعدا پرنده ترسناکی رفت خونه و تاجش زد و دیگر دیر شده بود. پیتزا رفته.  قهرمان آنها شده بود. لیلی دوست داشتند.. به صدای‌ یک‌پسربچه‌ای به نام جری. جری شیر را در بشقاب امروز را دوست دارم. این باغ رو ول کرد که به باغ
<br>

ابتدا درباره نحوه پیاده سازی ای که برای هر کدام انجام دادم توضیح می دهو. برای laplace هر context که دیده می شود، به تمام کلماتی که در دیکشنری بعد هستند و بعد از آن می آیند یک واحد اضافه کردم که احتمال هیچ کلمه ای برای آن context صفر نشود (منظورم از context همان n-1 توکن اول در هر ngram است.) <br>

برای backoff هم از stupid backoff استفاده کردم (که در اسلاید های درس آمده) که در آن اگر یک context دیده نشده بود، به سراغ context کوتاه تر می رویم و احتمال آن را با یک ضریب λ ضرب می کنیم. در این حالت اگر باز هم context کوتاه تر دیده نشده بود، باز هم به سراغ context کوتاه تر می رویم و همینطور ادامه می دهیم تا به unigram برسیم. <br>

برای interpolation هم که طبق فرمول، احتمال ها تا رسیدن به unigram محاسبه می شوند و با ضرب کردن در ضرایب از پیش تعیین شده و جمع شدن با هم، احتمال نهایی بدست می آید.<br>


حال هر کدام را با توجه به متن های تولید شده شان بررسی می کنم. متن تولید شده با روش laplace دارای کلمات بی معنی زیادی است و پیوستگی معنایی جمله هم حفظ نشده است و حتی در context های چهار توکنی هم کلمات بی ربط به هم وجود دارند. دلیلش این است که ما در هر مرحله برای انتخاب توکن بعدی، داریم به تمام توکن هایی که احتمالشان صفر هست هم یک احتمال کوچکی می دهیم و چون متن اصلی ما بزرگ است و تعداد توکن های صفر بسیار زیاد است، داریم از احتمال توکن هایی که واقعا بالا هستند کم می کنیم و به احتمال توکن های صفر اضافه می کنیم و در واقع با این کار تنوع بالا می رود اما این تنوع در جهت تولد کلمات بی معنا و مفهوم و بعضا بی ربط به هم  است که بی فایده است.در واقع عملا داریم انتخاب هر توکن را شبیه انتخاب رندوم می کنیم (مخصوصا اینکه روش توکن کردن من byte level است و کلا ممکن است در سطح subword عبارات رندوم انتخاب شوند و در نتیجه یک سری از کلمات هم خودشان بی معنی بشوند).در نتیجه این روش برای تولید متن در تسک ما که تعداد توکن های byte level زیاد است و همچنین زبان فارسی است، مناسب نیست.<br>

برای backoff اوضاع تولید متن بسیار بهتر می شود و انسجام درون context ها نسبت به حالت بدون smoothing بسیار بالاتر می رود. دلیلش این است که در این روش اگر ngram بلندتر دیده نشده باشد، به سراغ ngram های کوتاه تر می رویم و احتمال آنها را با یک ضریب کمتر در نظر می گیریم. بنابراین احتمال توکن های بی معنی کاهش پیدا می کند و متن انسجام بیشتری دارد. البته باز هم به دلیل ذات ngram، انسجام کلی متن پس از چند کلمه از بین می رود و متن پرش پیدا می کند و موضوع قبلی فراموش می شود اما نسبت به حالت بدون smoothing بسیار بهتر است و انسجام محلی و درون کلمات بهتر حفظ شده است.<br>

برای حالت interpolation انسجام متنی درون context ها نسبت به backoff کمتر می شود اما تنوع کلمات تولیدی بالاتر می رود. در واقع در این روش احتمال همه‌ی مرتبه‌ها را به طور همزمان با وزن‌های مشخص ترکیب می شوند تا توزیع نرم‌تر و پیوسته‌تری بسازد. مزیت اصلی آن این است که برای واژه‌ها یا عبارات دیده نشده، هنوز احتمال غیرصفری تولید می‌کند و از گسستگی مدل جلوگیری می‌کند، هرچند اگر وزن‌ها درست تنظیم نشوند، ممکن است وابستگی‌های محلی ضعیف شوند و متن کمی مبهم یا کم‌ارتباط به نظر برسد.


برای حالت معمولی (unsmoothed) هم که قبلا گفته بودم perplexity برابر با 86 بود که نشان می دهد مدل در هر مرحله تقریبا 86 کلمه با احتمال یکسان را در نظر می گیرد که نشان می دهد مدل نسبتا خوب است و اطلاعی از وابستگی بین کلمات دارد و قطعیت آن در تولید کلمه مناسب و دارای احتمال بالا در هر مرحله نسبتا خوب است.<br>

برای مقایسه perplexity ها مشاهده می کنیم که مقدار به دست آمده برای laplace بسیار زیاد و برابر 1783 است و این نشان می دهد که به صورت میانگین مدل در هر مرحله تقریبا 1783 کلمه با احتمال یکسان را در نظر می گیرد که نشان می دهد مدل ضعیف است و عملا اطلاعی از وابستگی بین کلمات ندارد و قطعیت آن در تولید کلمه مناسب و دارای احتمال بالا در هر مرحله کم است که با توجه به مطالبی که در بالا اشاره کردم که توکن ها با احتمال صفر هم دارای احتمال می شوند و توکن ها با احتمال بالا، احتمالشان کاهش می یابد، این موضوع قابل درک است.<br>

برای حالت backoff، این مقدار برابر 100 است که از laplace به مراتب بهتر است .


حال برای حالت interpolation، مقدار perplexity برابر 30 شده است که نشان می دهد مدل اطلاع خوبی از وابستگی بین کلمات دارد و قطعیت آن در تولید کلمه مناسب و دارای احتمال بالا در هر مرحله بسیار خوب است. این موضوع با توجه به اینکه در این روش از تمام context ها استفاده می کنیم و احتمال هر کلمه را با توجه به تمام context های ممکن محاسبه می کنیم و سپس با ضرایب از پیش تعیین شده آنها را جمع می کنیم، قابل درک است.<br>

با توجه به این اعداذ، برای مقایسه این مدل ها می توان گفت که مدل interpolation بهترین عملکرد را دارد و انسجام محلی و درون کلمات بهتر حفظ شده است و همچنین مقدار perplexity آن هم کمترین مقدار است که نشان می دهد مدل اطلاع خوبی از وابستگی بین کلمات دارد و قطعیت آن در تولید کلمه مناسب و دارای احتمال بالا در هر مرحله خوب است. پس از آن مدل backoff قرار دارد که آن هم perplexity خوبی دارد و همانطور که در جملات چاپ شده دیدیم و در بالا هم توضیح دادم، انسجام محلی بهتری از interpolation در تولید متن دارد اما تنوع کلمات تولیدی interpolation بالاتر است.. مدل unsmoothed هم عملکرد نسبتا خوبی دارد اما مدل laplace ضعیف ترین عملکرد را دارد و انسجام محلی و درون کلمات حفظ نشده است و همچنین مقدار perplexity آن هم بسیار زیاد است که نشان می دهد مدل اطلاعی از وابستگی بین کلمات ندارد و قطعیت آن در تولید کلمه مناسب و دارای احتمال بالا در هر مرحله کم است. 
</div>

## <div style="text-align: center; direction: rtl; font-family: Vazir;">پیاده‌سازی Temperature</div>


<p dir="rtl" style="line-height: 1.8; text-align: right; padding:10px; background-color:#6B7280;  border-radius: 12px; border: 2px solid rgb(2, 34, 22); font-family: Vazir;">
در مورد تاثیر Temperature در مدل‌های زبانی توضیح‌دهید.
<br>
به هنگام Sampling از N-gram، برای آن Temperature تعریف کنید و پیاده‌سازی‌های لازم را انجام دهید.
<br>
با قرار دادن کمترین Temperature و با بیشترین Temperature، سه‌بار خروجی‌هایی به طول ۲۰ توکن تولید کنید. (برای هر حالت سه‌بار) و سپس تاثیر Temperature در خروجی‌ها را تحلیل کنید.
</p>


<p dir='rtl' style="line-height: 2.0; text-align: right; font-family: Vazir; font-size: 16px; margin-top: 20px; color: white; background-color:rgb(0, 40, 30); padding: 30px; border-radius: 8px;">
🎯 <b>خروجی مورد انتظار:</b><br>
- متن‌های تولید‌شده با Temperature بالا و پایین (برای هریک ۳ عدد متن تولید شده)
</p>

In [125]:
print("Texts generated by 4-gram model with no smoothing with temperature = 0.1: \n")
for i in range(3):
    print(f"Sample {i + 1}: ")
    no_smoothing_tokens = model.generate(length=20, smoothing=None, temperature=0.1)
    no_smoothing_text = bpe_tokenizer.decode(no_smoothing_tokens)
    print(no_smoothing_text)

Texts generated by 4-gram model with no smoothing with temperature = 0.1: 

Sample 1: 
 یک روز، یک گربه بزرگ و یک سگ در پارک بازی می‌کردند. آنها دوست داشتند با
Sample 2: 
 یک روز، یک گربه بزرگ و یک گربه کوچک به نام تیم بود. تیم دوست داشت با دوستانش
Sample 3: 
 یک روز، یک گربه بزرگ و یک گربه کوچک به نام تیم بود. تیم دوست داشت با اسباب


In [127]:
print("Texts generated by 4-gram model with no smoothing with temperature = 3: \n")
for i in range(3):
    print(f"Sample {i + 1}: ")
    no_smoothing_tokens = model.generate(length=20, smoothing=None, temperature=3)
    no_smoothing_text = bpe_tokenizer.decode(no_smoothing_tokens)
    print(no_smoothing_text)

Texts generated by 4-gram model with no smoothing with temperature = 3: 

Sample 1: 
 همچنین‌باری، دزدی بی‌ضرر کرد. او دیگر خوشحال نبود و می توانست گرمای آفتاب را
Sample 2: 
 دوسته کوچولو دخترک یک گربه پشمالو برای گردش به پارک رفت.‌ وقتی به کوه نگاه کنند. پشت پرده
Sample 3: 
 بازی را چنین بود، پسر کوچولویی از خواب بیدار شوند. صبح روز ویژه اش یاد داشته باشد چقدر


$$P_i = \frac{e^{(logits_i / T)}}{\sum_{j} e^{(logits_j / T)}}$$


<div dir="rtl" style="background:#fffbe6;font-family: Vazir;border:1px dashed #f0ad4e;padding:12px;border-radius:8px;color:#111;line-height:1.9;overflow:auto;max-width:100%;box-sizing:border-box;">
✍️ <b>پاسخ تشریحی زیربخش ششم:</b><br>

temperature یک پارامتر است که در نمونه‌گیری از توزیع احتمالاتی مدل‌های زبانی استفاده می‌شود تا میزان تصادفی بودن یا تنوع خروجی تولید شده را کنترل کند. با تغییر مقدار temperature، می‌توان تاثیر قابل توجهی بر روی کیفیت و تنوع متن تولید شده داشت. فرمول آن را ر بالا آورده ام
که در آن T همان temperature است و logits_i هم لگاریتم احتمال کلمه i ام است.<br>
 وقتی temperature کمتر از 1 باشد (مثلا 0.5 یا 0.1)، توزیع احتمالات تیزتر می‌شود که به این معنی است که کلمات با احتمال بالاتر حتی احتمال بیشتری پیدا می‌کنند و کلمات با احتمال پایین‌تر احتمال بسیار کمی خواهند داشت. در نتیجه، متن تولید شده معمولا منطقی‌تر و قابل پیش‌بینی‌تر خواهد بود، اما ممکن است تنوع کمتری داشته باشد و متن ممکن است تکراری یا کلیشه‌ای شود. همچنین اگر بیشتر از 1 باشد، توزیع احتمالات نرم‌تر می‌شود و کلمات با احتمال پایین‌تر نیز شانس بیشتری برای انتخاب شدن پیدا می‌کنند، که می‌تواند به تولید متن‌های خلاقانه‌تر و متنوع‌تر منجر شود.<br>

پیاده سازی مربوط به آن را در کلاس NgramSmoothed اضافه کردم که در آن ابتدا logits را با توجه به temperature تنظیم می کنیم و سپس با استفاده از softmax، توزیع احتمالات جدید را محاسبه می کنیم و سپس از این توزیع برای نمونه‌گیری کلمه بعدی استفاده می کنیم.<br>

وقتی temperature را برابر یک مقدار کوچک مانند 0.1 قرار دادم، همانطور که مشاهده می شود، سه جمله تولید شده بسیار شبیه به هم هستند و تقریبا یکسان اند. دلیل این موضوع این است که با کم کردن temperature، توزیع احتمالات تیزتر می‌شود و کلمات با احتمال بالاتر حتی احتمال بیشتری پیدا می‌کنند و کلمات با احتمال پایین‌تر احتمال بسیار کمی خواهند داشت. در نتیجه، مدل تمایل دارد که کلمات با احتمال بالا را انتخاب کند و این باعث می‌شود که متن تولید شده بسیار قابل پیش‌بینی و تکراری شود. در واقع در هر مرحله، مدل به احتمال زیاد کلمات مشابهی را تولید می‌کند و این باعث می‌شود که تنوع متن کاهش یابد.<br>

اما وقتی temperature را بالا بردم و عددی مانند 3 قرار دادم، مشاهده می شود که سه جمله تولید شده بسیار متفاوت از هم هستند و تنوع زیادی دارند. دلیل این موضوع این است که با افزایش temperature، توزیع احتمالات نرم‌تر می‌شود و کلمات با احتمال پایین‌تر نیز شانس بیشتری برای انتخاب شدن پیدا می‌کنند. در نتیجه، مدل تمایل دارد که کلمات متنوع‌تری را انتخاب کند و این باعث می‌شود که متن تولید شده خلاقانه‌تر و متنوع‌تر باشد. در واقع در هر مرحله، مدل ممکن است کلمات مختلفی را تولید کند و این باعث می‌شود که تنوع متن افزایش یابد. در واقع اتفاقی که از لحاظ فرمولی می افتد این است که با افزایش temperature، لگاریتم احتمال کلمات به گونه‌ای تغییر می‌کند که کلمات با احتمال پایین‌تر نیز شانس بیشتری برای انتخاب شدن پیدا می‌کنند و این باعث می‌شود که متن تولید شده تنوع بیشتری داشته باشد.<br>


</div>

<p dir='rtl'>
لینک چت های انجام شده با gpt:

 <a href='https://chatgpt.com/share/68f1fbb8-0478-8007-b12c-9cedf569b64b'>https://chatgpt.com/share/68f1fbb8-0478-8007-b12c-9cedf569b64b</a><br>
 <a href='https://chatgpt.com/share/68fc48be-091c-8003-ad90-1ff7de9eff3e'>https://chatgpt.com/share/68fc48be-091c-8003-ad90-1ff7de9eff3e</a>
</p>

# <h1 style="text-align: right;">**نکات مهم و قوانین تحویل**</h1>


<div dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px; text-align: right;">
    <p style="text-align: right;" dir="rtl"><strong dir="rtl">مهلت تحویل :</strong> 10 آبان</p>
</div>
<h4 dir="rtl" style="font-family: Vazir; width: 85%;">فایل ارسالی شما باید با فرمت زیر نامگذاری شود: <code>NLP_CA{n}_{LASTNAME}_{STUDENTID}.ipynb</code></h4>
<h4 dir="rtl" style="font-family: Vazir; width: 85%;">نحوه انجام تمرین:</h4>
<ul dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
  <li>سلول‌های کد با برچسب <code>WRITE YOUR CODE HERE</code> را تکمیل کنید.</li>
  <li>برای پاسخ‌های متنی، متن <code>{{پاسخ_خود_را_اینجا_بنویسید}}</code> را با پاسخ خود جایگزین کنید.</li>
</ul>
<h4 dir="rtl" style="font-family: Vazir; width: 85%;">صداقت علمی:</h4> <ul dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;"> <li>ما نوت‌بوک‌های تعداد مشخصی از دانشجویان که به صورت تصادفی انتخاب می‌شوند، بررسی خواهیم کرد. این بررسی‌ها اطمینان حاصل می‌کنند که کدی که نوشتید واقعاً پاسخ‌های موجود در نوت‌بوک شما را تولید می‌کند. اگر پاسخ‌های صحیح را در نوت‌بوک خود بدون کدی که واقعاً آن پاسخ‌ها را تولید کند تحویل دهید، این یک مورد جدی از عدم صداقت علمی محسوب می‌شود.</li> <li>ما همچنین بررسی‌های خودکاری را برای تشخیص سرقت علمی در نوت‌بوک‌های کولب انجام خواهیم داد. کپی کردن کد از دیگران نیز یک مورد جدی از عدم صداقت علمی محسوب می‌شود.</li> </ul>
<h4 dir="rtl" style="font-family: Vazir; width: 85%;">توضیحات تکمیلی:</h4> <ul dir="rtl" style="font-family: Vazir; width: 85%; font-size: 16px;">
<li>
خوانایی و دقت بررسی‌ها در گزارش نهایی از اهمیت ویژه‌ای برخوردار است. به تمرین‌هایی که به صورت کاغذی تحویل داده شوند یا به صورت عکس در سایت بارگذاری شوند، ترتیب اثری داده نخواهد شد.</li>
<li>
 همه‌ی کدهای پیوست گزارش بایستی قابلیت اجرای مجدد داشته باشند. در صورتی که برای اجرا مجدد آن‌ها نیاز به تنظیمات خاصی می‌باشد، بایستی تنظیمات مورد نیاز را نیز در گزارش خود ذکر کنید.  دقت کنید که  تمامی کدها باید توسط شما اجرا شده باشند و نتایج اجرا در فایل کدهای ارسالی مشخص باشد. به کدهایی که نتایج اجرای آن‌ها در فایل ارسالی مشخص نباشد نمره‌ای تعلق نمی‌گیرد.
</li>
<li>توجه کنید این تمرین باید به صورت تک‌نفره انجام شود و پاسخ‌های ارائه شده باید نتیجه فعالیت فرد نویسنده باشد (همفکری و به اتفاق هم نوشتن تمرین نیز ممنوع است). در صورت مشاهده
 تشابه به همه افراد مشارکت‌کننده، نمره تمرین صفر و به استاد گزارش می‌گردد.
 </li>

 <li>
لطفاً تمامی پاسخ‌های متنی خود را با <b>فونت وزیر (Vazir)</b> و به‌صورت <b>راست‌چین</b> بنویسید.  
از استفاده از فونت‌های پیش‌فرض خودداری کنید تا ظاهر نوت‌بوک شما یک‌دست و خوانا باشد.  
در بخش‌های تشریحی، سعی کنید پاسخ‌ها را کامل، منسجم و با رعایت نگارش فارسی بنویسید.  
همچنین، به چینش تمیز سلول‌ها و اجرای درست کدها توجه کنید تا تمرین شما با فرمت خواسته‌شده و استاندارد ارائه شود.
</li>
 <li>برای مطالعه بیشتر درباره‌ی فرمت Markdown می‌توانید از <a href="https://github.com/tajaddini/Persian-Markdown/blob/master/learn-MD.md">این لینک</a> مطالعه کنید.
 </li>
 </ul>
    

 </div>
